/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.UpdateChannelConnectionRequestDto;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerUpdateChannelConnectionRequest;
import org.openapis.openapi.operations.ChannelConnectionsControllerUpdateChannelConnection;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final ChannelConnectionsControllerUpdateChannelConnectionRequest.Builder pojoBuilder;
    private ChannelConnectionsControllerUpdateChannelConnectionRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = ChannelConnectionsControllerUpdateChannelConnectionRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder identifier(@Nonnull String identifier) {
        this.pojoBuilder.identifier(identifier);
        this._setterCalled = true;
        return this;
    }

    public ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder body(@Nonnull UpdateChannelConnectionRequestDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private ChannelConnectionsControllerUpdateChannelConnectionRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<ChannelConnectionsControllerUpdateChannelConnectionResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<ChannelConnectionsControllerUpdateChannelConnectionRequest, ChannelConnectionsControllerUpdateChannelConnectionResponse> operation
              = new ChannelConnectionsControllerUpdateChannelConnection.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
