/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1DeleteEnvironmentRequest;
import org.openapis.openapi.operations.EnvironmentsControllerV1DeleteEnvironment;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class EnvironmentsControllerV1DeleteEnvironmentRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final EnvironmentsControllerV1DeleteEnvironmentRequest.Builder pojoBuilder;
    private EnvironmentsControllerV1DeleteEnvironmentRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public EnvironmentsControllerV1DeleteEnvironmentRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = EnvironmentsControllerV1DeleteEnvironmentRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public EnvironmentsControllerV1DeleteEnvironmentRequestBuilder environmentId(@Nonnull String environmentId) {
        this.pojoBuilder.environmentId(environmentId);
        this._setterCalled = true;
        return this;
    }

    public EnvironmentsControllerV1DeleteEnvironmentRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public EnvironmentsControllerV1DeleteEnvironmentRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private EnvironmentsControllerV1DeleteEnvironmentRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public EnvironmentsControllerV1DeleteEnvironmentRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<EnvironmentsControllerV1DeleteEnvironmentResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<EnvironmentsControllerV1DeleteEnvironmentRequest, EnvironmentsControllerV1DeleteEnvironmentResponse> operation
              = new EnvironmentsControllerV1DeleteEnvironment.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
