/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.CreateIntegrationRequestDto;
import org.openapis.openapi.models.operations.IntegrationsControllerCreateIntegrationRequest;
import org.openapis.openapi.operations.IntegrationsControllerCreateIntegration;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class IntegrationsControllerCreateIntegrationRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final IntegrationsControllerCreateIntegrationRequest.Builder pojoBuilder;
    private IntegrationsControllerCreateIntegrationRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public IntegrationsControllerCreateIntegrationRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = IntegrationsControllerCreateIntegrationRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public IntegrationsControllerCreateIntegrationRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public IntegrationsControllerCreateIntegrationRequestBuilder body(@Nonnull CreateIntegrationRequestDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public IntegrationsControllerCreateIntegrationRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private IntegrationsControllerCreateIntegrationRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public IntegrationsControllerCreateIntegrationRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<IntegrationsControllerCreateIntegrationResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<IntegrationsControllerCreateIntegrationRequest, IntegrationsControllerCreateIntegrationResponse> operation
              = new IntegrationsControllerCreateIntegration.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
