/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.operations.LayoutsControllerGetRequest;
import org.openapis.openapi.operations.LayoutsControllerGet;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class LayoutsControllerGetRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final LayoutsControllerGetRequest.Builder pojoBuilder;
    private LayoutsControllerGetRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public LayoutsControllerGetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = LayoutsControllerGetRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public LayoutsControllerGetRequestBuilder layoutId(@Nonnull String layoutId) {
        this.pojoBuilder.layoutId(layoutId);
        this._setterCalled = true;
        return this;
    }

    public LayoutsControllerGetRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public LayoutsControllerGetRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private LayoutsControllerGetRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public LayoutsControllerGetRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<LayoutsControllerGetResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<LayoutsControllerGetRequest, LayoutsControllerGetResponse> operation
              = new LayoutsControllerGet.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
