/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.CreateSubscriberRequestDto;
import org.openapis.openapi.models.operations.SubscribersControllerCreateSubscriberRequest;
import org.openapis.openapi.operations.SubscribersControllerCreateSubscriber;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class SubscribersControllerCreateSubscriberRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final SubscribersControllerCreateSubscriberRequest.Builder pojoBuilder;
    private SubscribersControllerCreateSubscriberRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public SubscribersControllerCreateSubscriberRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = SubscribersControllerCreateSubscriberRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public SubscribersControllerCreateSubscriberRequestBuilder failIfExists(@Nullable Boolean failIfExists) {
        this.pojoBuilder.failIfExists(failIfExists);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerCreateSubscriberRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerCreateSubscriberRequestBuilder body(@Nonnull CreateSubscriberRequestDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerCreateSubscriberRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private SubscribersControllerCreateSubscriberRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public SubscribersControllerCreateSubscriberRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<SubscribersControllerCreateSubscriberResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<SubscribersControllerCreateSubscriberRequest, SubscribersControllerCreateSubscriberResponse> operation
              = new SubscribersControllerCreateSubscriber.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
