/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.operations.SubscribersControllerListSubscriberTopicsRequest;
import org.openapis.openapi.operations.SubscribersControllerListSubscriberTopics;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class SubscribersControllerListSubscriberTopicsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private SubscribersControllerListSubscriberTopicsRequest request;
    private final Options.Builder optionsBuilder;

    public SubscribersControllerListSubscriberTopicsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public SubscribersControllerListSubscriberTopicsRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public SubscribersControllerListSubscriberTopicsRequestBuilder request(@Nonnull SubscribersControllerListSubscriberTopicsRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private SubscribersControllerListSubscriberTopicsRequest _buildRequest() {
        return this.request;
    }
    
    public SubscribersControllerListSubscriberTopicsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<SubscribersControllerListSubscriberTopicsResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<SubscribersControllerListSubscriberTopicsRequest, SubscribersControllerListSubscriberTopicsResponse> operation
              = new SubscribersControllerListSubscriberTopics.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
