/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.operations.SubscribersV1ControllerMarkActionAsSeenRequest;
import org.openapis.openapi.operations.SubscribersV1ControllerMarkActionAsSeen;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class SubscribersV1ControllerMarkActionAsSeenRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private SubscribersV1ControllerMarkActionAsSeenRequest request;
    private final Options.Builder optionsBuilder;

    public SubscribersV1ControllerMarkActionAsSeenRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public SubscribersV1ControllerMarkActionAsSeenRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public SubscribersV1ControllerMarkActionAsSeenRequestBuilder request(@Nonnull SubscribersV1ControllerMarkActionAsSeenRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private SubscribersV1ControllerMarkActionAsSeenRequest _buildRequest() {
        return this.request;
    }
    
    public SubscribersV1ControllerMarkActionAsSeenRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<SubscribersV1ControllerMarkActionAsSeenResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<SubscribersV1ControllerMarkActionAsSeenRequest, SubscribersV1ControllerMarkActionAsSeenResponse> operation
              = new SubscribersV1ControllerMarkActionAsSeen.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
