/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.UpdateSubscriberChannelRequestDto;
import org.openapis.openapi.models.operations.SubscribersV1ControllerModifySubscriberChannelRequest;
import org.openapis.openapi.operations.SubscribersV1ControllerModifySubscriberChannel;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class SubscribersV1ControllerModifySubscriberChannelRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final SubscribersV1ControllerModifySubscriberChannelRequest.Builder pojoBuilder;
    private SubscribersV1ControllerModifySubscriberChannelRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = SubscribersV1ControllerModifySubscriberChannelRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder subscriberId(@Nonnull String subscriberId) {
        this.pojoBuilder.subscriberId(subscriberId);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder body(@Nonnull UpdateSubscriberChannelRequestDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private SubscribersV1ControllerModifySubscriberChannelRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<SubscribersV1ControllerModifySubscriberChannelResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<SubscribersV1ControllerModifySubscriberChannelRequest, SubscribersV1ControllerModifySubscriberChannelResponse> operation
              = new SubscribersV1ControllerModifySubscriberChannel.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
