/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.operations.Criticality;
import org.openapis.openapi.models.operations.SubscribersControllerGetSubscriberPreferencesRequest;
import org.openapis.openapi.operations.SubscribersControllerGetSubscriberPreferences;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class SubscribersControllerGetSubscriberPreferencesRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final SubscribersControllerGetSubscriberPreferencesRequest.Builder pojoBuilder;
    private SubscribersControllerGetSubscriberPreferencesRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public SubscribersControllerGetSubscriberPreferencesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = SubscribersControllerGetSubscriberPreferencesRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public SubscribersControllerGetSubscriberPreferencesRequestBuilder subscriberId(@Nonnull String subscriberId) {
        this.pojoBuilder.subscriberId(subscriberId);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerGetSubscriberPreferencesRequestBuilder criticality(@Nullable Criticality criticality) {
        this.pojoBuilder.criticality(criticality);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerGetSubscriberPreferencesRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerGetSubscriberPreferencesRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private SubscribersControllerGetSubscriberPreferencesRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public SubscribersControllerGetSubscriberPreferencesRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<SubscribersControllerGetSubscriberPreferencesResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<SubscribersControllerGetSubscriberPreferencesRequest, SubscribersControllerGetSubscriberPreferencesResponse> operation
              = new SubscribersControllerGetSubscriberPreferences.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
