/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.DeleteTopicSubscriptionsRequestDto;
import org.openapis.openapi.models.operations.TopicsControllerDeleteTopicSubscriptionsRequest;
import org.openapis.openapi.operations.TopicsControllerDeleteTopicSubscriptions;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class TopicsControllerDeleteTopicSubscriptionsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final TopicsControllerDeleteTopicSubscriptionsRequest.Builder pojoBuilder;
    private TopicsControllerDeleteTopicSubscriptionsRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public TopicsControllerDeleteTopicSubscriptionsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = TopicsControllerDeleteTopicSubscriptionsRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public TopicsControllerDeleteTopicSubscriptionsRequestBuilder topicKey(@Nonnull String topicKey) {
        this.pojoBuilder.topicKey(topicKey);
        this._setterCalled = true;
        return this;
    }

    public TopicsControllerDeleteTopicSubscriptionsRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public TopicsControllerDeleteTopicSubscriptionsRequestBuilder body(@Nonnull DeleteTopicSubscriptionsRequestDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public TopicsControllerDeleteTopicSubscriptionsRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private TopicsControllerDeleteTopicSubscriptionsRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public TopicsControllerDeleteTopicSubscriptionsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<TopicsControllerDeleteTopicSubscriptionsResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<TopicsControllerDeleteTopicSubscriptionsRequest, TopicsControllerDeleteTopicSubscriptionsResponse> operation
              = new TopicsControllerDeleteTopicSubscriptions.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
