/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.operations.TranslationControllerGetMasterJsonEndpointRequest;
import org.openapis.openapi.operations.TranslationControllerGetMasterJsonEndpoint;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class TranslationControllerGetMasterJsonEndpointRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final TranslationControllerGetMasterJsonEndpointRequest.Builder pojoBuilder;
    private TranslationControllerGetMasterJsonEndpointRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public TranslationControllerGetMasterJsonEndpointRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = TranslationControllerGetMasterJsonEndpointRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public TranslationControllerGetMasterJsonEndpointRequestBuilder locale(@Nullable String locale) {
        this.pojoBuilder.locale(locale);
        this._setterCalled = true;
        return this;
    }

    public TranslationControllerGetMasterJsonEndpointRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public TranslationControllerGetMasterJsonEndpointRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private TranslationControllerGetMasterJsonEndpointRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public TranslationControllerGetMasterJsonEndpointRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<TranslationControllerGetMasterJsonEndpointResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<TranslationControllerGetMasterJsonEndpointRequest, TranslationControllerGetMasterJsonEndpointResponse> operation
              = new TranslationControllerGetMasterJsonEndpoint.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
