/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.IllegalArgumentException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import org.openapis.openapi.utils.GenericTypeIdResolver;


/**
 * ChannelEndpointsControllerCreateChannelEndpointRequestBodyTypeIdResolver
 * 
 * <p>Channel endpoint creation request. The structure varies based on the type field.
 */
public class ChannelEndpointsControllerCreateChannelEndpointRequestBodyTypeIdResolver extends GenericTypeIdResolver<ChannelEndpointsControllerCreateChannelEndpointRequestBody> {

    public ChannelEndpointsControllerCreateChannelEndpointRequestBodyTypeIdResolver() {
        super(UnknownChannelEndpointsControllerCreateChannelEndpointRequestBody.class);
        initializeTypeMap();
    }

    private void initializeTypeMap() {
        registerType("slack_channel", org.openapis.openapi.models.components.CreateSlackChannelEndpointDto.class);
        registerType("slack_user", org.openapis.openapi.models.components.CreateSlackUserEndpointDto.class);
        registerType("webhook", org.openapis.openapi.models.components.CreateWebhookEndpointDto.class);
        registerType("phone", org.openapis.openapi.models.components.CreatePhoneEndpointDto.class);
        registerType("ms_teams_channel", org.openapis.openapi.models.components.CreateMsTeamsChannelEndpointDto.class);
        registerType("ms_teams_user", org.openapis.openapi.models.components.CreateMsTeamsUserEndpointDto.class);
    }

    @Override
    public String idFromValue(Object value) {
        if (value == null) {
            return null;
        }
        
        // Handle known types by checking if they implement the discriminator method
        if (value instanceof ChannelEndpointsControllerCreateChannelEndpointRequestBody) {
            ChannelEndpointsControllerCreateChannelEndpointRequestBody discriminated = (ChannelEndpointsControllerCreateChannelEndpointRequestBody) value;
            return discriminated.type();
        }
        
        throw new IllegalArgumentException("Unknown value type: " + value.getClass().getName());
    }

    @Override
    public String getDescForKnownTypeIds() {
        return "ChannelEndpointsControllerCreateChannelEndpointRequestBody type resolver";
    }

}