/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.ContextsControllerListContexts;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class ContextsControllerListContextsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private ContextsControllerListContextsRequest request;
    private final Options.Builder optionsBuilder;

    public ContextsControllerListContextsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public ContextsControllerListContextsRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public ContextsControllerListContextsRequestBuilder request(@Nonnull ContextsControllerListContextsRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private ContextsControllerListContextsRequest _buildRequest() {
        return this.request;
    }
    
    public ContextsControllerListContextsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ContextsControllerListContextsResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<ContextsControllerListContextsRequest, ContextsControllerListContextsResponse> operation
              = new ContextsControllerListContexts.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
