/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.BulkTriggerEventDto;
import org.openapis.openapi.operations.EventsControllerTriggerBulk;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class EventsControllerTriggerBulkRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final EventsControllerTriggerBulkRequest.Builder pojoBuilder;
    private EventsControllerTriggerBulkRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public EventsControllerTriggerBulkRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = EventsControllerTriggerBulkRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public EventsControllerTriggerBulkRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public EventsControllerTriggerBulkRequestBuilder body(@Nonnull BulkTriggerEventDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public EventsControllerTriggerBulkRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private EventsControllerTriggerBulkRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public EventsControllerTriggerBulkRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public EventsControllerTriggerBulkResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<EventsControllerTriggerBulkRequest, EventsControllerTriggerBulkResponse> operation
              = new EventsControllerTriggerBulk.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
