/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.IntegrationsControllerAutoConfigureIntegration;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class IntegrationsControllerAutoConfigureIntegrationRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final IntegrationsControllerAutoConfigureIntegrationRequest.Builder pojoBuilder;
    private IntegrationsControllerAutoConfigureIntegrationRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public IntegrationsControllerAutoConfigureIntegrationRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = IntegrationsControllerAutoConfigureIntegrationRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public IntegrationsControllerAutoConfigureIntegrationRequestBuilder integrationId(@Nonnull String integrationId) {
        this.pojoBuilder.integrationId(integrationId);
        this._setterCalled = true;
        return this;
    }

    public IntegrationsControllerAutoConfigureIntegrationRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public IntegrationsControllerAutoConfigureIntegrationRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private IntegrationsControllerAutoConfigureIntegrationRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public IntegrationsControllerAutoConfigureIntegrationRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public IntegrationsControllerAutoConfigureIntegrationResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<IntegrationsControllerAutoConfigureIntegrationRequest, IntegrationsControllerAutoConfigureIntegrationResponse> operation
              = new IntegrationsControllerAutoConfigureIntegration.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
