/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.DuplicateLayoutDto;
import org.openapis.openapi.operations.LayoutsControllerDuplicate;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class LayoutsControllerDuplicateRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final LayoutsControllerDuplicateRequest.Builder pojoBuilder;
    private LayoutsControllerDuplicateRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public LayoutsControllerDuplicateRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = LayoutsControllerDuplicateRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public LayoutsControllerDuplicateRequestBuilder layoutId(@Nonnull String layoutId) {
        this.pojoBuilder.layoutId(layoutId);
        this._setterCalled = true;
        return this;
    }

    public LayoutsControllerDuplicateRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public LayoutsControllerDuplicateRequestBuilder body(@Nonnull DuplicateLayoutDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public LayoutsControllerDuplicateRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private LayoutsControllerDuplicateRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public LayoutsControllerDuplicateRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public LayoutsControllerDuplicateResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<LayoutsControllerDuplicateRequest, LayoutsControllerDuplicateResponse> operation
              = new LayoutsControllerDuplicate.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
