/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class SubscribersControllerGetSubscriberPreferencesRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=subscriberId")
    private String subscriberId;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=criticality")
    private Criticality criticality;

    /**
     * A header for idempotency purposes
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")
    private String idempotencyKey;

    @JsonCreator
    public SubscribersControllerGetSubscriberPreferencesRequest(
            @Nonnull String subscriberId,
            @Nullable Criticality criticality,
            @Nullable String idempotencyKey) {
        this.subscriberId = Optional.ofNullable(subscriberId)
            .orElseThrow(() -> new IllegalArgumentException("subscriberId cannot be null"));
        this.criticality = Optional.ofNullable(criticality)
            .orElse(Builder._SINGLETON_VALUE_Criticality.value());
        this.idempotencyKey = idempotencyKey;
    }
    
    public SubscribersControllerGetSubscriberPreferencesRequest(
            @Nonnull String subscriberId) {
        this(subscriberId, null, null);
    }

    public String subscriberId() {
        return this.subscriberId;
    }

    public Optional<Criticality> criticality() {
        return Optional.ofNullable(this.criticality);
    }

    /**
     * A header for idempotency purposes
     */
    public Optional<String> idempotencyKey() {
        return Optional.ofNullable(this.idempotencyKey);
    }

    public static Builder builder() {
        return new Builder();
    }


    public SubscribersControllerGetSubscriberPreferencesRequest withSubscriberId(@Nonnull String subscriberId) {
        this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
        return this;
    }


    public SubscribersControllerGetSubscriberPreferencesRequest withCriticality(@Nullable Criticality criticality) {
        this.criticality = criticality;
        return this;
    }


    /**
     * A header for idempotency purposes
     */
    public SubscribersControllerGetSubscriberPreferencesRequest withIdempotencyKey(@Nullable String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscribersControllerGetSubscriberPreferencesRequest other = (SubscribersControllerGetSubscriberPreferencesRequest) o;
        return 
            Utils.enhancedDeepEquals(this.subscriberId, other.subscriberId) &&
            Utils.enhancedDeepEquals(this.criticality, other.criticality) &&
            Utils.enhancedDeepEquals(this.idempotencyKey, other.idempotencyKey);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            subscriberId, criticality, idempotencyKey);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscribersControllerGetSubscriberPreferencesRequest.class,
                "subscriberId", subscriberId,
                "criticality", criticality,
                "idempotencyKey", idempotencyKey);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String subscriberId;

        private Criticality criticality;

        private String idempotencyKey;

        private Builder() {
          // force use of static builder() method
        }

        public Builder subscriberId(@Nonnull String subscriberId) {
            this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
            return this;
        }

        public Builder criticality(@Nullable Criticality criticality) {
            this.criticality = criticality;
            return this;
        }

        /**
         * A header for idempotency purposes
         */
        public Builder idempotencyKey(@Nullable String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        public SubscribersControllerGetSubscriberPreferencesRequest build() {
            return new SubscribersControllerGetSubscriberPreferencesRequest(
                subscriberId, criticality, idempotencyKey);
        }


        private static final LazySingletonValue<Criticality> _SINGLETON_VALUE_Criticality =
                new LazySingletonValue<>(
                        "criticality",
                        "\"nonCritical\"",
                        new TypeReference<Criticality>() {});
    }
}
