/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.UpdateSubscriberOnlineFlagRequestDto;
import org.openapis.openapi.operations.SubscribersV1ControllerUpdateSubscriberOnlineFlag;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest.Builder pojoBuilder;
    private SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder subscriberId(@Nonnull String subscriberId) {
        this.pojoBuilder.subscriberId(subscriberId);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder body(@Nonnull UpdateSubscriberOnlineFlagRequestDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest, SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse> operation
              = new SubscribersV1ControllerUpdateSubscriberOnlineFlag.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
