/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.TopicsControllerGetTopic;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class TopicsControllerGetTopicRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final TopicsControllerGetTopicRequest.Builder pojoBuilder;
    private TopicsControllerGetTopicRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public TopicsControllerGetTopicRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = TopicsControllerGetTopicRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public TopicsControllerGetTopicRequestBuilder topicKey(@Nonnull String topicKey) {
        this.pojoBuilder.topicKey(topicKey);
        this._setterCalled = true;
        return this;
    }

    public TopicsControllerGetTopicRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public TopicsControllerGetTopicRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private TopicsControllerGetTopicRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public TopicsControllerGetTopicRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public TopicsControllerGetTopicResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<TopicsControllerGetTopicRequest, TopicsControllerGetTopicResponse> operation
              = new TopicsControllerGetTopic.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
