/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.TranslationControllerGetSingleTranslation;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class TranslationControllerGetSingleTranslationRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final TranslationControllerGetSingleTranslationRequest.Builder pojoBuilder;
    private TranslationControllerGetSingleTranslationRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public TranslationControllerGetSingleTranslationRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = TranslationControllerGetSingleTranslationRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public TranslationControllerGetSingleTranslationRequestBuilder resourceType(@Nonnull TranslationControllerGetSingleTranslationResourceType resourceType) {
        this.pojoBuilder.resourceType(resourceType);
        this._setterCalled = true;
        return this;
    }

    public TranslationControllerGetSingleTranslationRequestBuilder resourceId(@Nonnull String resourceId) {
        this.pojoBuilder.resourceId(resourceId);
        this._setterCalled = true;
        return this;
    }

    public TranslationControllerGetSingleTranslationRequestBuilder locale(@Nonnull String locale) {
        this.pojoBuilder.locale(locale);
        this._setterCalled = true;
        return this;
    }

    public TranslationControllerGetSingleTranslationRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public TranslationControllerGetSingleTranslationRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private TranslationControllerGetSingleTranslationRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public TranslationControllerGetSingleTranslationRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public TranslationControllerGetSingleTranslationResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<TranslationControllerGetSingleTranslationRequest, TranslationControllerGetSingleTranslationResponse> operation
              = new TranslationControllerGetSingleTranslation.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
