/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.PatchWorkflowDto;
import org.openapis.openapi.operations.WorkflowControllerPatchWorkflow;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class WorkflowControllerPatchWorkflowRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final WorkflowControllerPatchWorkflowRequest.Builder pojoBuilder;
    private WorkflowControllerPatchWorkflowRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public WorkflowControllerPatchWorkflowRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = WorkflowControllerPatchWorkflowRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public WorkflowControllerPatchWorkflowRequestBuilder workflowId(@Nonnull String workflowId) {
        this.pojoBuilder.workflowId(workflowId);
        this._setterCalled = true;
        return this;
    }

    public WorkflowControllerPatchWorkflowRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public WorkflowControllerPatchWorkflowRequestBuilder body(@Nonnull PatchWorkflowDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public WorkflowControllerPatchWorkflowRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private WorkflowControllerPatchWorkflowRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public WorkflowControllerPatchWorkflowRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public WorkflowControllerPatchWorkflowResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<WorkflowControllerPatchWorkflowRequest, WorkflowControllerPatchWorkflowResponse> operation
              = new WorkflowControllerPatchWorkflow.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
