/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Object;
import java.lang.String;
import org.openapis.openapi.models.operations.InboundWebhooksControllerHandleWebhookRequest;
import org.openapis.openapi.models.operations.InboundWebhooksControllerHandleWebhookRequestBuilder;
import org.openapis.openapi.models.operations.InboundWebhooksControllerHandleWebhookResponse;
import org.openapis.openapi.operations.InboundWebhooksControllerHandleWebhook;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class Activity {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncActivity asyncSDK;

    Activity(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncActivity(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncActivity async() {
        return asyncSDK;
    }

    /**
     * Track activity and engagement events
     * 
     * <p>Track activity and engagement events for a specific delivery provider
     * 
     * @return The call builder
     */
    public InboundWebhooksControllerHandleWebhookRequestBuilder track() {
        return new InboundWebhooksControllerHandleWebhookRequestBuilder(sdkConfiguration);
    }

    /**
     * Track activity and engagement events
     * 
     * <p>Track activity and engagement events for a specific delivery provider
     * 
     * @param environmentId The environment identifier
     * @param integrationId The integration identifier for the delivery provider
     * @param body Webhook event payload from the delivery provider
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public InboundWebhooksControllerHandleWebhookResponse track(
            @Nonnull String environmentId, @Nonnull String integrationId,
            @Nonnull Object body) {
        return track(environmentId, integrationId, null,
            body, null);
    }

    /**
     * Track activity and engagement events
     * 
     * <p>Track activity and engagement events for a specific delivery provider
     * 
     * @param environmentId The environment identifier
     * @param integrationId The integration identifier for the delivery provider
     * @param idempotencyKey A header for idempotency purposes
     * @param body Webhook event payload from the delivery provider
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public InboundWebhooksControllerHandleWebhookResponse track(
            @Nonnull String environmentId, @Nonnull String integrationId,
            @Nullable String idempotencyKey, @Nonnull Object body,
            @Nullable Options options) {
        InboundWebhooksControllerHandleWebhookRequest request = new InboundWebhooksControllerHandleWebhookRequest(
                environmentId, integrationId, idempotencyKey,
                body);
        RequestOperation<InboundWebhooksControllerHandleWebhookRequest, InboundWebhooksControllerHandleWebhookResponse> operation
              = new InboundWebhooksControllerHandleWebhook.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
