/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.components.CreateLayoutDto;
import org.openapis.openapi.models.components.DuplicateLayoutDto;
import org.openapis.openapi.models.components.LayoutPreviewRequestDto;
import org.openapis.openapi.models.components.UpdateLayoutDto;
import org.openapis.openapi.models.operations.LayoutsControllerCreateRequest;
import org.openapis.openapi.models.operations.LayoutsControllerDeleteRequest;
import org.openapis.openapi.models.operations.LayoutsControllerDuplicateRequest;
import org.openapis.openapi.models.operations.LayoutsControllerGeneratePreviewRequest;
import org.openapis.openapi.models.operations.LayoutsControllerGetRequest;
import org.openapis.openapi.models.operations.LayoutsControllerGetUsageRequest;
import org.openapis.openapi.models.operations.LayoutsControllerListRequest;
import org.openapis.openapi.models.operations.LayoutsControllerUpdateRequest;
import org.openapis.openapi.models.operations.async.LayoutsControllerCreateRequestBuilder;
import org.openapis.openapi.models.operations.async.LayoutsControllerCreateResponse;
import org.openapis.openapi.models.operations.async.LayoutsControllerDeleteRequestBuilder;
import org.openapis.openapi.models.operations.async.LayoutsControllerDeleteResponse;
import org.openapis.openapi.models.operations.async.LayoutsControllerDuplicateRequestBuilder;
import org.openapis.openapi.models.operations.async.LayoutsControllerDuplicateResponse;
import org.openapis.openapi.models.operations.async.LayoutsControllerGeneratePreviewRequestBuilder;
import org.openapis.openapi.models.operations.async.LayoutsControllerGeneratePreviewResponse;
import org.openapis.openapi.models.operations.async.LayoutsControllerGetRequestBuilder;
import org.openapis.openapi.models.operations.async.LayoutsControllerGetResponse;
import org.openapis.openapi.models.operations.async.LayoutsControllerGetUsageRequestBuilder;
import org.openapis.openapi.models.operations.async.LayoutsControllerGetUsageResponse;
import org.openapis.openapi.models.operations.async.LayoutsControllerListRequestBuilder;
import org.openapis.openapi.models.operations.async.LayoutsControllerListResponse;
import org.openapis.openapi.models.operations.async.LayoutsControllerUpdateRequestBuilder;
import org.openapis.openapi.models.operations.async.LayoutsControllerUpdateResponse;
import org.openapis.openapi.operations.LayoutsControllerCreate;
import org.openapis.openapi.operations.LayoutsControllerDelete;
import org.openapis.openapi.operations.LayoutsControllerDuplicate;
import org.openapis.openapi.operations.LayoutsControllerGeneratePreview;
import org.openapis.openapi.operations.LayoutsControllerGet;
import org.openapis.openapi.operations.LayoutsControllerGetUsage;
import org.openapis.openapi.operations.LayoutsControllerList;
import org.openapis.openapi.operations.LayoutsControllerUpdate;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;

/**
 * Layouts are reusable wrappers for your email notifications.
 * 
 * <p><a href="https://docs.novu.co/platform/workflow/layouts">https://docs.novu.co/platform/workflow/layouts</a>
 */
public class AsyncLayouts {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Layouts syncSDK;

    AsyncLayouts(Layouts syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Layouts sync() {
        return syncSDK;
    }


    /**
     * Create a layout
     * 
     * <p>Creates a new layout in the Novu Cloud environment
     * 
     * @return The async call builder
     */
    public LayoutsControllerCreateRequestBuilder create() {
        return new LayoutsControllerCreateRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a layout
     * 
     * <p>Creates a new layout in the Novu Cloud environment
     * 
     * @param body 
     * @return {@code CompletableFuture<LayoutsControllerCreateResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerCreateResponse> create(@Nonnull CreateLayoutDto body) {
        return create(null, body, null);
    }

    /**
     * Create a layout
     * 
     * <p>Creates a new layout in the Novu Cloud environment
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<LayoutsControllerCreateResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerCreateResponse> create(
            @Nullable String idempotencyKey, @Nonnull CreateLayoutDto body,
            @Nullable Options options) {
        LayoutsControllerCreateRequest request = new LayoutsControllerCreateRequest(idempotencyKey, body);
        AsyncRequestOperation<LayoutsControllerCreateRequest, LayoutsControllerCreateResponse> operation
              = new LayoutsControllerCreate.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * List all layouts
     * 
     * <p>Retrieves a list of layouts with optional filtering and pagination
     * 
     * @return The async call builder
     */
    public LayoutsControllerListRequestBuilder list() {
        return new LayoutsControllerListRequestBuilder(sdkConfiguration);
    }

    /**
     * List all layouts
     * 
     * <p>Retrieves a list of layouts with optional filtering and pagination
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<LayoutsControllerListResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerListResponse> list(@Nonnull LayoutsControllerListRequest request) {
        return list(request, null);
    }

    /**
     * List all layouts
     * 
     * <p>Retrieves a list of layouts with optional filtering and pagination
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<LayoutsControllerListResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerListResponse> list(@Nonnull LayoutsControllerListRequest request, @Nullable Options options) {
        AsyncRequestOperation<LayoutsControllerListRequest, LayoutsControllerListResponse> operation
              = new LayoutsControllerList.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Update a layout
     * 
     * <p>Updates the details of an existing layout, here **layoutId** is the identifier of the layout
     * 
     * @return The async call builder
     */
    public LayoutsControllerUpdateRequestBuilder update() {
        return new LayoutsControllerUpdateRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a layout
     * 
     * <p>Updates the details of an existing layout, here **layoutId** is the identifier of the layout
     * 
     * @param layoutId 
     * @param body 
     * @return {@code CompletableFuture<LayoutsControllerUpdateResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerUpdateResponse> update(@Nonnull String layoutId, @Nonnull UpdateLayoutDto body) {
        return update(
                layoutId, null, body,
                null);
    }

    /**
     * Update a layout
     * 
     * <p>Updates the details of an existing layout, here **layoutId** is the identifier of the layout
     * 
     * @param layoutId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<LayoutsControllerUpdateResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerUpdateResponse> update(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nonnull UpdateLayoutDto body, @Nullable Options options) {
        LayoutsControllerUpdateRequest request = new LayoutsControllerUpdateRequest(layoutId, idempotencyKey, body);
        AsyncRequestOperation<LayoutsControllerUpdateRequest, LayoutsControllerUpdateResponse> operation
              = new LayoutsControllerUpdate.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Retrieve a layout
     * 
     * <p>Fetches details of a specific layout by its unique identifier **layoutId**
     * 
     * @return The async call builder
     */
    public LayoutsControllerGetRequestBuilder retrieve() {
        return new LayoutsControllerGetRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a layout
     * 
     * <p>Fetches details of a specific layout by its unique identifier **layoutId**
     * 
     * @param layoutId 
     * @return {@code CompletableFuture<LayoutsControllerGetResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerGetResponse> retrieve(@Nonnull String layoutId) {
        return retrieve(layoutId, null, null);
    }

    /**
     * Retrieve a layout
     * 
     * <p>Fetches details of a specific layout by its unique identifier **layoutId**
     * 
     * @param layoutId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return {@code CompletableFuture<LayoutsControllerGetResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerGetResponse> retrieve(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        LayoutsControllerGetRequest request = new LayoutsControllerGetRequest(layoutId, idempotencyKey);
        AsyncRequestOperation<LayoutsControllerGetRequest, LayoutsControllerGetResponse> operation
              = new LayoutsControllerGet.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete a layout
     * 
     * <p>Removes a specific layout by its unique identifier **layoutId**
     * 
     * @return The async call builder
     */
    public LayoutsControllerDeleteRequestBuilder delete() {
        return new LayoutsControllerDeleteRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a layout
     * 
     * <p>Removes a specific layout by its unique identifier **layoutId**
     * 
     * @param layoutId The unique identifier of the layout
     * @return {@code CompletableFuture<LayoutsControllerDeleteResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerDeleteResponse> delete(@Nonnull String layoutId) {
        return delete(layoutId, null, null);
    }

    /**
     * Delete a layout
     * 
     * <p>Removes a specific layout by its unique identifier **layoutId**
     * 
     * @param layoutId The unique identifier of the layout
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return {@code CompletableFuture<LayoutsControllerDeleteResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerDeleteResponse> delete(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        LayoutsControllerDeleteRequest request = new LayoutsControllerDeleteRequest(layoutId, idempotencyKey);
        AsyncRequestOperation<LayoutsControllerDeleteRequest, LayoutsControllerDeleteResponse> operation
              = new LayoutsControllerDelete.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Duplicate a layout
     * 
     * <p>Duplicates a layout by its unique identifier **layoutId**. This will create a new layout with the
     * content of the original layout.
     * 
     * @return The async call builder
     */
    public LayoutsControllerDuplicateRequestBuilder duplicate() {
        return new LayoutsControllerDuplicateRequestBuilder(sdkConfiguration);
    }

    /**
     * Duplicate a layout
     * 
     * <p>Duplicates a layout by its unique identifier **layoutId**. This will create a new layout with the
     * content of the original layout.
     * 
     * @param layoutId 
     * @param body 
     * @return {@code CompletableFuture<LayoutsControllerDuplicateResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerDuplicateResponse> duplicate(@Nonnull String layoutId, @Nonnull DuplicateLayoutDto body) {
        return duplicate(
                layoutId, null, body,
                null);
    }

    /**
     * Duplicate a layout
     * 
     * <p>Duplicates a layout by its unique identifier **layoutId**. This will create a new layout with the
     * content of the original layout.
     * 
     * @param layoutId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<LayoutsControllerDuplicateResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerDuplicateResponse> duplicate(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nonnull DuplicateLayoutDto body, @Nullable Options options) {
        LayoutsControllerDuplicateRequest request = new LayoutsControllerDuplicateRequest(layoutId, idempotencyKey, body);
        AsyncRequestOperation<LayoutsControllerDuplicateRequest, LayoutsControllerDuplicateResponse> operation
              = new LayoutsControllerDuplicate.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Generate layout preview
     * 
     * <p>Generates a preview for a layout by its unique identifier **layoutId**
     * 
     * @return The async call builder
     */
    public LayoutsControllerGeneratePreviewRequestBuilder preview() {
        return new LayoutsControllerGeneratePreviewRequestBuilder(sdkConfiguration);
    }

    /**
     * Generate layout preview
     * 
     * <p>Generates a preview for a layout by its unique identifier **layoutId**
     * 
     * @param layoutId 
     * @param body 
     * @return {@code CompletableFuture<LayoutsControllerGeneratePreviewResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerGeneratePreviewResponse> preview(@Nonnull String layoutId, @Nonnull LayoutPreviewRequestDto body) {
        return preview(
                layoutId, null, body,
                null);
    }

    /**
     * Generate layout preview
     * 
     * <p>Generates a preview for a layout by its unique identifier **layoutId**
     * 
     * @param layoutId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<LayoutsControllerGeneratePreviewResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerGeneratePreviewResponse> preview(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nonnull LayoutPreviewRequestDto body, @Nullable Options options) {
        LayoutsControllerGeneratePreviewRequest request = new LayoutsControllerGeneratePreviewRequest(layoutId, idempotencyKey, body);
        AsyncRequestOperation<LayoutsControllerGeneratePreviewRequest, LayoutsControllerGeneratePreviewResponse> operation
              = new LayoutsControllerGeneratePreview.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get layout usage
     * 
     * <p>Retrieves information about workflows that use the specified layout by its unique identifier
     * **layoutId**
     * 
     * @return The async call builder
     */
    public LayoutsControllerGetUsageRequestBuilder getUsage() {
        return new LayoutsControllerGetUsageRequestBuilder(sdkConfiguration);
    }

    /**
     * Get layout usage
     * 
     * <p>Retrieves information about workflows that use the specified layout by its unique identifier
     * **layoutId**
     * 
     * @param layoutId 
     * @return {@code CompletableFuture<LayoutsControllerGetUsageResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerGetUsageResponse> getUsage(@Nonnull String layoutId) {
        return getUsage(layoutId, null, null);
    }

    /**
     * Get layout usage
     * 
     * <p>Retrieves information about workflows that use the specified layout by its unique identifier
     * **layoutId**
     * 
     * @param layoutId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return {@code CompletableFuture<LayoutsControllerGetUsageResponse>} - The async response
     */
    public CompletableFuture<LayoutsControllerGetUsageResponse> getUsage(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        LayoutsControllerGetUsageRequest request = new LayoutsControllerGetUsageRequest(layoutId, idempotencyKey);
        AsyncRequestOperation<LayoutsControllerGetUsageRequest, LayoutsControllerGetUsageResponse> operation
              = new LayoutsControllerGetUsage.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
