/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.operations.SubscribersV1ControllerDeleteSubscriberCredentialsRequest;
import org.openapis.openapi.models.operations.async.SubscribersV1ControllerDeleteSubscriberCredentialsRequestBuilder;
import org.openapis.openapi.models.operations.async.SubscribersV1ControllerDeleteSubscriberCredentialsResponse;
import org.openapis.openapi.operations.SubscribersV1ControllerDeleteSubscriberCredentials;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class AsyncCredentials {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Credentials syncSDK;

    AsyncCredentials(Credentials syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Credentials sync() {
        return syncSDK;
    }


    /**
     * Delete provider credentials
     * 
     * <p>Delete subscriber credentials for a provider such as **slack** and **FCM** by **providerId**.
     * This action is irreversible and will remove the credentials for the provider for particular
     * **subscriberId**.
     * 
     * @return The async call builder
     */
    public SubscribersV1ControllerDeleteSubscriberCredentialsRequestBuilder delete() {
        return new SubscribersV1ControllerDeleteSubscriberCredentialsRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete provider credentials
     * 
     * <p>Delete subscriber credentials for a provider such as **slack** and **FCM** by **providerId**.
     * This action is irreversible and will remove the credentials for the provider for particular
     * **subscriberId**.
     * 
     * @param subscriberId 
     * @param providerId 
     * @return {@code CompletableFuture<SubscribersV1ControllerDeleteSubscriberCredentialsResponse>} - The async response
     */
    public CompletableFuture<SubscribersV1ControllerDeleteSubscriberCredentialsResponse> delete(@Nonnull String subscriberId, @Nonnull String providerId) {
        return delete(
                subscriberId, providerId, null,
                null);
    }

    /**
     * Delete provider credentials
     * 
     * <p>Delete subscriber credentials for a provider such as **slack** and **FCM** by **providerId**.
     * This action is irreversible and will remove the credentials for the provider for particular
     * **subscriberId**.
     * 
     * @param subscriberId 
     * @param providerId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return {@code CompletableFuture<SubscribersV1ControllerDeleteSubscriberCredentialsResponse>} - The async response
     */
    public CompletableFuture<SubscribersV1ControllerDeleteSubscriberCredentialsResponse> delete(
            @Nonnull String subscriberId, @Nonnull String providerId,
            @Nullable String idempotencyKey, @Nullable Options options) {
        SubscribersV1ControllerDeleteSubscriberCredentialsRequest request = new SubscribersV1ControllerDeleteSubscriberCredentialsRequest(subscriberId, providerId, idempotencyKey);
        AsyncRequestOperation<SubscribersV1ControllerDeleteSubscriberCredentialsRequest, SubscribersV1ControllerDeleteSubscriberCredentialsResponse> operation
              = new SubscribersV1ControllerDeleteSubscriberCredentials.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
