/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.operations.SubscribersControllerListSubscriberTopicsRequest;
import org.openapis.openapi.models.operations.async.SubscribersControllerListSubscriberTopicsRequestBuilder;
import org.openapis.openapi.models.operations.async.SubscribersControllerListSubscriberTopicsResponse;
import org.openapis.openapi.operations.SubscribersControllerListSubscriberTopics;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class AsyncSubscribersTopics {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final SubscribersTopics syncSDK;

    AsyncSubscribersTopics(SubscribersTopics syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public SubscribersTopics sync() {
        return syncSDK;
    }


    /**
     * Retrieve subscriber subscriptions
     * 
     * <p>Retrieve subscriber's topic subscriptions by its unique key identifier **subscriberId**.
     * Checkout all available filters in the query section.
     * 
     * @return The async call builder
     */
    public SubscribersControllerListSubscriberTopicsRequestBuilder list() {
        return new SubscribersControllerListSubscriberTopicsRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve subscriber subscriptions
     * 
     * <p>Retrieve subscriber's topic subscriptions by its unique key identifier **subscriberId**.
     * Checkout all available filters in the query section.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<SubscribersControllerListSubscriberTopicsResponse>} - The async response
     */
    public CompletableFuture<SubscribersControllerListSubscriberTopicsResponse> list(@Nonnull SubscribersControllerListSubscriberTopicsRequest request) {
        return list(request, null);
    }

    /**
     * Retrieve subscriber subscriptions
     * 
     * <p>Retrieve subscriber's topic subscriptions by its unique key identifier **subscriberId**.
     * Checkout all available filters in the query section.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<SubscribersControllerListSubscriberTopicsResponse>} - The async response
     */
    public CompletableFuture<SubscribersControllerListSubscriberTopicsResponse> list(@Nonnull SubscribersControllerListSubscriberTopicsRequest request, @Nullable Options options) {
        AsyncRequestOperation<SubscribersControllerListSubscriberTopicsRequest, SubscribersControllerListSubscriberTopicsResponse> operation
              = new SubscribersControllerListSubscriberTopics.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
