/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.operations.Criticality;
import org.openapis.openapi.models.operations.SubscribersControllerGetSubscriberPreferencesRequest;
import org.openapis.openapi.models.operations.async.SubscribersControllerGetSubscriberPreferencesRequestBuilder;
import org.openapis.openapi.models.operations.async.SubscribersControllerGetSubscriberPreferencesResponse;
import org.openapis.openapi.operations.SubscribersControllerGetSubscriberPreferences;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class AsyncPreferences {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Preferences syncSDK;

    AsyncPreferences(Preferences syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Preferences sync() {
        return syncSDK;
    }


    /**
     * Retrieve subscriber preferences
     * 
     * <p>Retrieve subscriber channel preferences by its unique key identifier **subscriberId**.
     * This API returns all five channels preferences for all workflows and global preferences.
     * 
     * @return The async call builder
     */
    public SubscribersControllerGetSubscriberPreferencesRequestBuilder getPreferences() {
        return new SubscribersControllerGetSubscriberPreferencesRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve subscriber preferences
     * 
     * <p>Retrieve subscriber channel preferences by its unique key identifier **subscriberId**.
     * This API returns all five channels preferences for all workflows and global preferences.
     * 
     * @param subscriberId 
     * @return {@code CompletableFuture<SubscribersControllerGetSubscriberPreferencesResponse>} - The async response
     */
    public CompletableFuture<SubscribersControllerGetSubscriberPreferencesResponse> getPreferences(@Nonnull String subscriberId) {
        return getPreferences(
                subscriberId, null, null,
                null);
    }

    /**
     * Retrieve subscriber preferences
     * 
     * <p>Retrieve subscriber channel preferences by its unique key identifier **subscriberId**.
     * This API returns all five channels preferences for all workflows and global preferences.
     * 
     * @param subscriberId 
     * @param criticality 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return {@code CompletableFuture<SubscribersControllerGetSubscriberPreferencesResponse>} - The async response
     */
    public CompletableFuture<SubscribersControllerGetSubscriberPreferencesResponse> getPreferences(
            @Nonnull String subscriberId, @Nullable Criticality criticality,
            @Nullable String idempotencyKey, @Nullable Options options) {
        SubscribersControllerGetSubscriberPreferencesRequest request = new SubscribersControllerGetSubscriberPreferencesRequest(subscriberId, criticality, idempotencyKey);
        AsyncRequestOperation<SubscribersControllerGetSubscriberPreferencesRequest, SubscribersControllerGetSubscriberPreferencesResponse> operation
              = new SubscribersControllerGetSubscriberPreferences.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
