/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.components.CreateTranslationRequestDto;
import org.openapis.openapi.models.components.ImportMasterJsonRequestDto;
import org.openapis.openapi.models.operations.TranslationControllerCreateTranslationEndpointRequest;
import org.openapis.openapi.models.operations.TranslationControllerDeleteTranslationEndpointRequest;
import org.openapis.openapi.models.operations.TranslationControllerDeleteTranslationEndpointResourceType;
import org.openapis.openapi.models.operations.TranslationControllerGetSingleTranslationRequest;
import org.openapis.openapi.models.operations.TranslationControllerGetSingleTranslationResourceType;
import org.openapis.openapi.models.operations.TranslationControllerImportMasterJsonEndpointRequest;
import org.openapis.openapi.models.operations.TranslationControllerUploadMasterJsonEndpointRequest;
import org.openapis.openapi.models.operations.TranslationControllerUploadMasterJsonEndpointRequestBody;
import org.openapis.openapi.models.operations.TranslationControllerUploadTranslationFilesRequest;
import org.openapis.openapi.models.operations.TranslationControllerUploadTranslationFilesRequestBody;
import org.openapis.openapi.models.operations.async.TranslationControllerCreateTranslationEndpointRequestBuilder;
import org.openapis.openapi.models.operations.async.TranslationControllerCreateTranslationEndpointResponse;
import org.openapis.openapi.models.operations.async.TranslationControllerDeleteTranslationEndpointRequestBuilder;
import org.openapis.openapi.models.operations.async.TranslationControllerDeleteTranslationEndpointResponse;
import org.openapis.openapi.models.operations.async.TranslationControllerGetSingleTranslationRequestBuilder;
import org.openapis.openapi.models.operations.async.TranslationControllerGetSingleTranslationResponse;
import org.openapis.openapi.models.operations.async.TranslationControllerImportMasterJsonEndpointRequestBuilder;
import org.openapis.openapi.models.operations.async.TranslationControllerImportMasterJsonEndpointResponse;
import org.openapis.openapi.models.operations.async.TranslationControllerUploadMasterJsonEndpointRequestBuilder;
import org.openapis.openapi.models.operations.async.TranslationControllerUploadMasterJsonEndpointResponse;
import org.openapis.openapi.models.operations.async.TranslationControllerUploadTranslationFilesRequestBuilder;
import org.openapis.openapi.models.operations.async.TranslationControllerUploadTranslationFilesResponse;
import org.openapis.openapi.operations.TranslationControllerCreateTranslationEndpoint;
import org.openapis.openapi.operations.TranslationControllerDeleteTranslationEndpoint;
import org.openapis.openapi.operations.TranslationControllerGetSingleTranslation;
import org.openapis.openapi.operations.TranslationControllerImportMasterJsonEndpoint;
import org.openapis.openapi.operations.TranslationControllerUploadMasterJsonEndpoint;
import org.openapis.openapi.operations.TranslationControllerUploadTranslationFiles;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class AsyncTranslations {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncGroups groups;
    private final Translations syncSDK;

    AsyncTranslations(Translations syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.groups = new AsyncGroups(syncSDK.groups(), this.sdkConfiguration);
        this.syncSDK = syncSDK;
    }

    public final AsyncGroups groups() {
        return groups;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Translations sync() {
        return syncSDK;
    }


    /**
     * Create a translation
     * 
     * <p>Create a translation for a specific workflow and locale, if the translation already exists, it will
     * be updated
     * 
     * @return The async call builder
     */
    public TranslationControllerCreateTranslationEndpointRequestBuilder create() {
        return new TranslationControllerCreateTranslationEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a translation
     * 
     * <p>Create a translation for a specific workflow and locale, if the translation already exists, it will
     * be updated
     * 
     * @param body 
     * @return {@code CompletableFuture<TranslationControllerCreateTranslationEndpointResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerCreateTranslationEndpointResponse> create(@Nonnull CreateTranslationRequestDto body) {
        return create(null, body, null);
    }

    /**
     * Create a translation
     * 
     * <p>Create a translation for a specific workflow and locale, if the translation already exists, it will
     * be updated
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<TranslationControllerCreateTranslationEndpointResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerCreateTranslationEndpointResponse> create(
            @Nullable String idempotencyKey, @Nonnull CreateTranslationRequestDto body,
            @Nullable Options options) {
        TranslationControllerCreateTranslationEndpointRequest request = new TranslationControllerCreateTranslationEndpointRequest(idempotencyKey, body);
        AsyncRequestOperation<TranslationControllerCreateTranslationEndpointRequest, TranslationControllerCreateTranslationEndpointResponse> operation
              = new TranslationControllerCreateTranslationEndpoint.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Retrieve a translation
     * 
     * <p>Retrieve a specific translation by resource type, resource ID and locale
     * 
     * @return The async call builder
     */
    public TranslationControllerGetSingleTranslationRequestBuilder get() {
        return new TranslationControllerGetSingleTranslationRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a translation
     * 
     * <p>Retrieve a specific translation by resource type, resource ID and locale
     * 
     * @param resourceType Resource type
     * @param resourceId Resource ID
     * @param locale Locale code
     * @return {@code CompletableFuture<TranslationControllerGetSingleTranslationResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerGetSingleTranslationResponse> get(
            @Nonnull TranslationControllerGetSingleTranslationResourceType resourceType, @Nonnull String resourceId,
            @Nonnull String locale) {
        return get(
                resourceType, resourceId, locale,
                null, null);
    }

    /**
     * Retrieve a translation
     * 
     * <p>Retrieve a specific translation by resource type, resource ID and locale
     * 
     * @param resourceType Resource type
     * @param resourceId Resource ID
     * @param locale Locale code
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return {@code CompletableFuture<TranslationControllerGetSingleTranslationResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerGetSingleTranslationResponse> get(
            @Nonnull TranslationControllerGetSingleTranslationResourceType resourceType, @Nonnull String resourceId,
            @Nonnull String locale, @Nullable String idempotencyKey,
            @Nullable Options options) {
        TranslationControllerGetSingleTranslationRequest request = new TranslationControllerGetSingleTranslationRequest(
                resourceType, resourceId, locale,
                idempotencyKey);
        AsyncRequestOperation<TranslationControllerGetSingleTranslationRequest, TranslationControllerGetSingleTranslationResponse> operation
              = new TranslationControllerGetSingleTranslation.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete a translation
     * 
     * <p>Delete a specific translation by resource type, resource ID and locale
     * 
     * @return The async call builder
     */
    public TranslationControllerDeleteTranslationEndpointRequestBuilder delete() {
        return new TranslationControllerDeleteTranslationEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a translation
     * 
     * <p>Delete a specific translation by resource type, resource ID and locale
     * 
     * @param resourceType Resource type
     * @param resourceId Resource ID
     * @param locale Locale code
     * @return {@code CompletableFuture<TranslationControllerDeleteTranslationEndpointResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerDeleteTranslationEndpointResponse> delete(
            @Nonnull TranslationControllerDeleteTranslationEndpointResourceType resourceType, @Nonnull String resourceId,
            @Nonnull String locale) {
        return delete(
                resourceType, resourceId, locale,
                null, null);
    }

    /**
     * Delete a translation
     * 
     * <p>Delete a specific translation by resource type, resource ID and locale
     * 
     * @param resourceType Resource type
     * @param resourceId Resource ID
     * @param locale Locale code
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return {@code CompletableFuture<TranslationControllerDeleteTranslationEndpointResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerDeleteTranslationEndpointResponse> delete(
            @Nonnull TranslationControllerDeleteTranslationEndpointResourceType resourceType, @Nonnull String resourceId,
            @Nonnull String locale, @Nullable String idempotencyKey,
            @Nullable Options options) {
        TranslationControllerDeleteTranslationEndpointRequest request = new TranslationControllerDeleteTranslationEndpointRequest(
                resourceType, resourceId, locale,
                idempotencyKey);
        AsyncRequestOperation<TranslationControllerDeleteTranslationEndpointRequest, TranslationControllerDeleteTranslationEndpointResponse> operation
              = new TranslationControllerDeleteTranslationEndpoint.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Upload translation files
     * 
     * <p>Upload one or more JSON translation files for a specific workflow. Files name must match the locale,
     * e.g. en_US.json.
     * 
     * <p>Supports both "files" and "files[]" field names for backwards compatibility.
     * 
     * @return The async call builder
     */
    public TranslationControllerUploadTranslationFilesRequestBuilder upload() {
        return new TranslationControllerUploadTranslationFilesRequestBuilder(sdkConfiguration);
    }

    /**
     * Upload translation files
     * 
     * <p>Upload one or more JSON translation files for a specific workflow. Files name must match the locale,
     * e.g. en_US.json.
     * 
     * <p>Supports both "files" and "files[]" field names for backwards compatibility.
     * 
     * @param body 
     * @return {@code CompletableFuture<TranslationControllerUploadTranslationFilesResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerUploadTranslationFilesResponse> upload(@Nonnull TranslationControllerUploadTranslationFilesRequestBody body) {
        return upload(null, body, null);
    }

    /**
     * Upload translation files
     * 
     * <p>Upload one or more JSON translation files for a specific workflow. Files name must match the locale,
     * e.g. en_US.json.
     * 
     * <p>Supports both "files" and "files[]" field names for backwards compatibility.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<TranslationControllerUploadTranslationFilesResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerUploadTranslationFilesResponse> upload(
            @Nullable String idempotencyKey, @Nonnull TranslationControllerUploadTranslationFilesRequestBody body,
            @Nullable Options options) {
        TranslationControllerUploadTranslationFilesRequest request = new TranslationControllerUploadTranslationFilesRequest(idempotencyKey, body);
        AsyncRequestOperation<TranslationControllerUploadTranslationFilesRequest, TranslationControllerUploadTranslationFilesResponse> operation
              = new TranslationControllerUploadTranslationFiles.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Import master translations JSON
     * 
     * <p>Import translations for multiple workflows from master JSON format for a specific locale
     * 
     * @return The async call builder
     */
    public TranslationControllerImportMasterJsonEndpointRequestBuilder importMasterJson() {
        return new TranslationControllerImportMasterJsonEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Import master translations JSON
     * 
     * <p>Import translations for multiple workflows from master JSON format for a specific locale
     * 
     * @param body 
     * @return {@code CompletableFuture<TranslationControllerImportMasterJsonEndpointResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerImportMasterJsonEndpointResponse> importMasterJson(@Nonnull ImportMasterJsonRequestDto body) {
        return importMasterJson(null, body, null);
    }

    /**
     * Import master translations JSON
     * 
     * <p>Import translations for multiple workflows from master JSON format for a specific locale
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<TranslationControllerImportMasterJsonEndpointResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerImportMasterJsonEndpointResponse> importMasterJson(
            @Nullable String idempotencyKey, @Nonnull ImportMasterJsonRequestDto body,
            @Nullable Options options) {
        TranslationControllerImportMasterJsonEndpointRequest request = new TranslationControllerImportMasterJsonEndpointRequest(idempotencyKey, body);
        AsyncRequestOperation<TranslationControllerImportMasterJsonEndpointRequest, TranslationControllerImportMasterJsonEndpointResponse> operation
              = new TranslationControllerImportMasterJsonEndpoint.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Upload master translations JSON file
     * 
     * <p>Upload a master JSON file containing translations for multiple workflows. Locale is automatically
     * detected from filename (e.g., en_US.json)
     * 
     * @return The async call builder
     */
    public TranslationControllerUploadMasterJsonEndpointRequestBuilder uploadMasterJson() {
        return new TranslationControllerUploadMasterJsonEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Upload master translations JSON file
     * 
     * <p>Upload a master JSON file containing translations for multiple workflows. Locale is automatically
     * detected from filename (e.g., en_US.json)
     * 
     * @param body 
     * @return {@code CompletableFuture<TranslationControllerUploadMasterJsonEndpointResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerUploadMasterJsonEndpointResponse> uploadMasterJson(@Nonnull TranslationControllerUploadMasterJsonEndpointRequestBody body) {
        return uploadMasterJson(null, body, null);
    }

    /**
     * Upload master translations JSON file
     * 
     * <p>Upload a master JSON file containing translations for multiple workflows. Locale is automatically
     * detected from filename (e.g., en_US.json)
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<TranslationControllerUploadMasterJsonEndpointResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerUploadMasterJsonEndpointResponse> uploadMasterJson(
            @Nullable String idempotencyKey, @Nonnull TranslationControllerUploadMasterJsonEndpointRequestBody body,
            @Nullable Options options) {
        TranslationControllerUploadMasterJsonEndpointRequest request = new TranslationControllerUploadMasterJsonEndpointRequest(idempotencyKey, body);
        AsyncRequestOperation<TranslationControllerUploadMasterJsonEndpointRequest, TranslationControllerUploadMasterJsonEndpointResponse> operation
              = new TranslationControllerUploadMasterJsonEndpoint.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
