/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.components.BulkUpdateSubscriberPreferencesDto;
import org.openapis.openapi.models.operations.SubscribersControllerBulkUpdateSubscriberPreferencesRequest;
import org.openapis.openapi.models.operations.async.SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder;
import org.openapis.openapi.models.operations.async.SubscribersControllerBulkUpdateSubscriberPreferencesResponse;
import org.openapis.openapi.operations.SubscribersControllerBulkUpdateSubscriberPreferences;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class AsyncSubscribersPreferences {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final SubscribersPreferences syncSDK;

    AsyncSubscribersPreferences(SubscribersPreferences syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public SubscribersPreferences sync() {
        return syncSDK;
    }


    /**
     * Bulk update subscriber preferences
     * 
     * <p>Bulk update subscriber preferences by its unique key identifier **subscriberId**.
     * This API allows updating multiple workflow preferences in a single request.
     * 
     * @return The async call builder
     */
    public SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder bulkUpdate() {
        return new SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder(sdkConfiguration);
    }

    /**
     * Bulk update subscriber preferences
     * 
     * <p>Bulk update subscriber preferences by its unique key identifier **subscriberId**.
     * This API allows updating multiple workflow preferences in a single request.
     * 
     * @param subscriberId 
     * @param body 
     * @return {@code CompletableFuture<SubscribersControllerBulkUpdateSubscriberPreferencesResponse>} - The async response
     */
    public CompletableFuture<SubscribersControllerBulkUpdateSubscriberPreferencesResponse> bulkUpdate(@Nonnull String subscriberId, @Nonnull BulkUpdateSubscriberPreferencesDto body) {
        return bulkUpdate(
                subscriberId, null, body,
                null);
    }

    /**
     * Bulk update subscriber preferences
     * 
     * <p>Bulk update subscriber preferences by its unique key identifier **subscriberId**.
     * This API allows updating multiple workflow preferences in a single request.
     * 
     * @param subscriberId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<SubscribersControllerBulkUpdateSubscriberPreferencesResponse>} - The async response
     */
    public CompletableFuture<SubscribersControllerBulkUpdateSubscriberPreferencesResponse> bulkUpdate(
            @Nonnull String subscriberId, @Nullable String idempotencyKey,
            @Nonnull BulkUpdateSubscriberPreferencesDto body, @Nullable Options options) {
        SubscribersControllerBulkUpdateSubscriberPreferencesRequest request = new SubscribersControllerBulkUpdateSubscriberPreferencesRequest(subscriberId, idempotencyKey, body);
        AsyncRequestOperation<SubscribersControllerBulkUpdateSubscriberPreferencesRequest, SubscribersControllerBulkUpdateSubscriberPreferencesResponse> operation
              = new SubscribersControllerBulkUpdateSubscriberPreferences.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
