/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.operations.TranslationControllerGetMasterJsonEndpointRequest;
import org.openapis.openapi.models.operations.async.TranslationControllerGetMasterJsonEndpointRequestBuilder;
import org.openapis.openapi.models.operations.async.TranslationControllerGetMasterJsonEndpointResponse;
import org.openapis.openapi.operations.TranslationControllerGetMasterJsonEndpoint;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class AsyncTranslationsMaster {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final TranslationsMaster syncSDK;

    AsyncTranslationsMaster(TranslationsMaster syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public TranslationsMaster sync() {
        return syncSDK;
    }


    /**
     * Retrieve master translations JSON
     * 
     * <p>Retrieve all translations for a locale in master JSON format organized by resourceId (workflowId)
     * 
     * @return The async call builder
     */
    public TranslationControllerGetMasterJsonEndpointRequestBuilder retrieve() {
        return new TranslationControllerGetMasterJsonEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve master translations JSON
     * 
     * <p>Retrieve all translations for a locale in master JSON format organized by resourceId (workflowId)
     * 
     * @return {@code CompletableFuture<TranslationControllerGetMasterJsonEndpointResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerGetMasterJsonEndpointResponse> retrieveDirect() {
        return retrieve(null, null, null);
    }

    /**
     * Retrieve master translations JSON
     * 
     * <p>Retrieve all translations for a locale in master JSON format organized by resourceId (workflowId)
     * 
     * @param locale Locale to export. If not provided, exports organization default locale
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return {@code CompletableFuture<TranslationControllerGetMasterJsonEndpointResponse>} - The async response
     */
    public CompletableFuture<TranslationControllerGetMasterJsonEndpointResponse> retrieve(
            @Nullable String locale, @Nullable String idempotencyKey,
            @Nullable Options options) {
        TranslationControllerGetMasterJsonEndpointRequest request = new TranslationControllerGetMasterJsonEndpointRequest(locale, idempotencyKey);
        AsyncRequestOperation<TranslationControllerGetMasterJsonEndpointRequest, TranslationControllerGetMasterJsonEndpointResponse> operation
              = new TranslationControllerGetMasterJsonEndpoint.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
