/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.operations.SubscribersV1ControllerGetNotificationsFeedRequest;
import org.openapis.openapi.models.operations.async.SubscribersV1ControllerGetNotificationsFeedRequestBuilder;
import org.openapis.openapi.models.operations.async.SubscribersV1ControllerGetNotificationsFeedResponse;
import org.openapis.openapi.operations.SubscribersV1ControllerGetNotificationsFeed;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class AsyncSubscribersNotifications {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final SubscribersNotifications syncSDK;

    AsyncSubscribersNotifications(SubscribersNotifications syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public SubscribersNotifications sync() {
        return syncSDK;
    }


    /**
     * Retrieve subscriber notifications
     * 
     * <p>Retrieve subscriber in-app (inbox) notifications by its unique key identifier **subscriberId**.
     * 
     * @return The async call builder
     */
    public SubscribersV1ControllerGetNotificationsFeedRequestBuilder getFeed() {
        return new SubscribersV1ControllerGetNotificationsFeedRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve subscriber notifications
     * 
     * <p>Retrieve subscriber in-app (inbox) notifications by its unique key identifier **subscriberId**.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<SubscribersV1ControllerGetNotificationsFeedResponse>} - The async response
     */
    public CompletableFuture<SubscribersV1ControllerGetNotificationsFeedResponse> getFeed(@Nonnull SubscribersV1ControllerGetNotificationsFeedRequest request) {
        return getFeed(request, null);
    }

    /**
     * Retrieve subscriber notifications
     * 
     * <p>Retrieve subscriber in-app (inbox) notifications by its unique key identifier **subscriberId**.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<SubscribersV1ControllerGetNotificationsFeedResponse>} - The async response
     */
    public CompletableFuture<SubscribersV1ControllerGetNotificationsFeedResponse> getFeed(@Nonnull SubscribersV1ControllerGetNotificationsFeedRequest request, @Nullable Options options) {
        AsyncRequestOperation<SubscribersV1ControllerGetNotificationsFeedRequest, SubscribersV1ControllerGetNotificationsFeedResponse> operation
              = new SubscribersV1ControllerGetNotificationsFeed.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
