/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.models.components.UpdateChannelEndpointRequestDto;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerCreateChannelEndpointRequest;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerCreateChannelEndpointRequestBody;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerCreateChannelEndpointRequestBuilder;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerCreateChannelEndpointResponse;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerDeleteChannelEndpointRequest;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerDeleteChannelEndpointRequestBuilder;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerDeleteChannelEndpointResponse;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerGetChannelEndpointRequest;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerGetChannelEndpointRequestBuilder;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerGetChannelEndpointResponse;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerListChannelEndpointsRequest;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerListChannelEndpointsRequestBuilder;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerListChannelEndpointsResponse;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerUpdateChannelEndpointRequest;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerUpdateChannelEndpointRequestBuilder;
import org.openapis.openapi.models.operations.ChannelEndpointsControllerUpdateChannelEndpointResponse;
import org.openapis.openapi.operations.ChannelEndpointsControllerCreateChannelEndpoint;
import org.openapis.openapi.operations.ChannelEndpointsControllerDeleteChannelEndpoint;
import org.openapis.openapi.operations.ChannelEndpointsControllerGetChannelEndpoint;
import org.openapis.openapi.operations.ChannelEndpointsControllerListChannelEndpoints;
import org.openapis.openapi.operations.ChannelEndpointsControllerUpdateChannelEndpoint;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class ChannelEndpoints {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncChannelEndpoints asyncSDK;

    ChannelEndpoints(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncChannelEndpoints(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncChannelEndpoints async() {
        return asyncSDK;
    }

    /**
     * List all channel endpoints
     * 
     * <p>List all channel endpoints for a resource based on query filters.
     * 
     * @return The call builder
     */
    public ChannelEndpointsControllerListChannelEndpointsRequestBuilder list() {
        return new ChannelEndpointsControllerListChannelEndpointsRequestBuilder(sdkConfiguration);
    }

    /**
     * List all channel endpoints
     * 
     * <p>List all channel endpoints for a resource based on query filters.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelEndpointsControllerListChannelEndpointsResponse list(@Nonnull ChannelEndpointsControllerListChannelEndpointsRequest request) {
        return list(request, null);
    }

    /**
     * List all channel endpoints
     * 
     * <p>List all channel endpoints for a resource based on query filters.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelEndpointsControllerListChannelEndpointsResponse list(@Nonnull ChannelEndpointsControllerListChannelEndpointsRequest request, @Nullable Options options) {
        RequestOperation<ChannelEndpointsControllerListChannelEndpointsRequest, ChannelEndpointsControllerListChannelEndpointsResponse> operation
              = new ChannelEndpointsControllerListChannelEndpoints.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create a channel endpoint
     * 
     * <p>Create a new channel endpoint for a resource.
     * 
     * @return The call builder
     */
    public ChannelEndpointsControllerCreateChannelEndpointRequestBuilder create() {
        return new ChannelEndpointsControllerCreateChannelEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a channel endpoint
     * 
     * <p>Create a new channel endpoint for a resource.
     * 
     * @param body Channel endpoint creation request. The structure varies based on the type field.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelEndpointsControllerCreateChannelEndpointResponse create(@Nonnull ChannelEndpointsControllerCreateChannelEndpointRequestBody body) {
        return create(null, body, null);
    }

    /**
     * Create a channel endpoint
     * 
     * <p>Create a new channel endpoint for a resource.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body Channel endpoint creation request. The structure varies based on the type field.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelEndpointsControllerCreateChannelEndpointResponse create(
            @Nullable String idempotencyKey, @Nonnull ChannelEndpointsControllerCreateChannelEndpointRequestBody body,
            @Nullable Options options) {
        ChannelEndpointsControllerCreateChannelEndpointRequest request = new ChannelEndpointsControllerCreateChannelEndpointRequest(idempotencyKey, body);
        RequestOperation<ChannelEndpointsControllerCreateChannelEndpointRequest, ChannelEndpointsControllerCreateChannelEndpointResponse> operation
              = new ChannelEndpointsControllerCreateChannelEndpoint.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a channel endpoint
     * 
     * <p>Retrieve a specific channel endpoint by its unique identifier.
     * 
     * @return The call builder
     */
    public ChannelEndpointsControllerGetChannelEndpointRequestBuilder get() {
        return new ChannelEndpointsControllerGetChannelEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a channel endpoint
     * 
     * <p>Retrieve a specific channel endpoint by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel endpoint
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelEndpointsControllerGetChannelEndpointResponse get(@Nonnull String identifier) {
        return get(identifier, null, null);
    }

    /**
     * Retrieve a channel endpoint
     * 
     * <p>Retrieve a specific channel endpoint by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel endpoint
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelEndpointsControllerGetChannelEndpointResponse get(
            @Nonnull String identifier, @Nullable String idempotencyKey,
            @Nullable Options options) {
        ChannelEndpointsControllerGetChannelEndpointRequest request = new ChannelEndpointsControllerGetChannelEndpointRequest(identifier, idempotencyKey);
        RequestOperation<ChannelEndpointsControllerGetChannelEndpointRequest, ChannelEndpointsControllerGetChannelEndpointResponse> operation
              = new ChannelEndpointsControllerGetChannelEndpoint.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a channel endpoint
     * 
     * <p>Update an existing channel endpoint by its unique identifier.
     * 
     * @return The call builder
     */
    public ChannelEndpointsControllerUpdateChannelEndpointRequestBuilder update() {
        return new ChannelEndpointsControllerUpdateChannelEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a channel endpoint
     * 
     * <p>Update an existing channel endpoint by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel endpoint
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelEndpointsControllerUpdateChannelEndpointResponse update(@Nonnull String identifier, @Nonnull UpdateChannelEndpointRequestDto body) {
        return update(identifier, null, body,
            null);
    }

    /**
     * Update a channel endpoint
     * 
     * <p>Update an existing channel endpoint by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel endpoint
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelEndpointsControllerUpdateChannelEndpointResponse update(
            @Nonnull String identifier, @Nullable String idempotencyKey,
            @Nonnull UpdateChannelEndpointRequestDto body, @Nullable Options options) {
        ChannelEndpointsControllerUpdateChannelEndpointRequest request = new ChannelEndpointsControllerUpdateChannelEndpointRequest(identifier, idempotencyKey, body);
        RequestOperation<ChannelEndpointsControllerUpdateChannelEndpointRequest, ChannelEndpointsControllerUpdateChannelEndpointResponse> operation
              = new ChannelEndpointsControllerUpdateChannelEndpoint.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete a channel endpoint
     * 
     * <p>Delete a specific channel endpoint by its unique identifier.
     * 
     * @return The call builder
     */
    public ChannelEndpointsControllerDeleteChannelEndpointRequestBuilder delete() {
        return new ChannelEndpointsControllerDeleteChannelEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a channel endpoint
     * 
     * <p>Delete a specific channel endpoint by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel endpoint
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelEndpointsControllerDeleteChannelEndpointResponse delete(@Nonnull String identifier) {
        return delete(identifier, null, null);
    }

    /**
     * Delete a channel endpoint
     * 
     * <p>Delete a specific channel endpoint by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel endpoint
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelEndpointsControllerDeleteChannelEndpointResponse delete(
            @Nonnull String identifier, @Nullable String idempotencyKey,
            @Nullable Options options) {
        ChannelEndpointsControllerDeleteChannelEndpointRequest request = new ChannelEndpointsControllerDeleteChannelEndpointRequest(identifier, idempotencyKey);
        RequestOperation<ChannelEndpointsControllerDeleteChannelEndpointRequest, ChannelEndpointsControllerDeleteChannelEndpointResponse> operation
              = new ChannelEndpointsControllerDeleteChannelEndpoint.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
