/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.models.components.CreateChannelConnectionRequestDto;
import org.openapis.openapi.models.components.UpdateChannelConnectionRequestDto;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerCreateChannelConnectionRequest;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerCreateChannelConnectionRequestBuilder;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerCreateChannelConnectionResponse;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerDeleteChannelConnectionRequest;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerDeleteChannelConnectionRequestBuilder;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerDeleteChannelConnectionResponse;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerGetChannelConnectionByIdentifierRequest;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerGetChannelConnectionByIdentifierRequestBuilder;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerGetChannelConnectionByIdentifierResponse;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerListChannelConnectionsRequest;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerListChannelConnectionsRequestBuilder;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerListChannelConnectionsResponse;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerUpdateChannelConnectionRequest;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder;
import org.openapis.openapi.models.operations.ChannelConnectionsControllerUpdateChannelConnectionResponse;
import org.openapis.openapi.operations.ChannelConnectionsControllerCreateChannelConnection;
import org.openapis.openapi.operations.ChannelConnectionsControllerDeleteChannelConnection;
import org.openapis.openapi.operations.ChannelConnectionsControllerGetChannelConnectionByIdentifier;
import org.openapis.openapi.operations.ChannelConnectionsControllerListChannelConnections;
import org.openapis.openapi.operations.ChannelConnectionsControllerUpdateChannelConnection;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class ChannelConnections {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncChannelConnections asyncSDK;

    ChannelConnections(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncChannelConnections(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncChannelConnections async() {
        return asyncSDK;
    }

    /**
     * List all channel connections
     * 
     * <p>List all channel connections for a resource.
     * 
     * @return The call builder
     */
    public ChannelConnectionsControllerListChannelConnectionsRequestBuilder list() {
        return new ChannelConnectionsControllerListChannelConnectionsRequestBuilder(sdkConfiguration);
    }

    /**
     * List all channel connections
     * 
     * <p>List all channel connections for a resource.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelConnectionsControllerListChannelConnectionsResponse list(@Nonnull ChannelConnectionsControllerListChannelConnectionsRequest request) {
        return list(request, null);
    }

    /**
     * List all channel connections
     * 
     * <p>List all channel connections for a resource.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelConnectionsControllerListChannelConnectionsResponse list(@Nonnull ChannelConnectionsControllerListChannelConnectionsRequest request, @Nullable Options options) {
        RequestOperation<ChannelConnectionsControllerListChannelConnectionsRequest, ChannelConnectionsControllerListChannelConnectionsResponse> operation
              = new ChannelConnectionsControllerListChannelConnections.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create a channel connection
     * 
     * <p>Create a new channel connection for a resource for given integration. Only one channel connection is
     * allowed per resource and integration.
     * 
     * @return The call builder
     */
    public ChannelConnectionsControllerCreateChannelConnectionRequestBuilder create() {
        return new ChannelConnectionsControllerCreateChannelConnectionRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a channel connection
     * 
     * <p>Create a new channel connection for a resource for given integration. Only one channel connection is
     * allowed per resource and integration.
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelConnectionsControllerCreateChannelConnectionResponse create(@Nonnull CreateChannelConnectionRequestDto body) {
        return create(null, body, null);
    }

    /**
     * Create a channel connection
     * 
     * <p>Create a new channel connection for a resource for given integration. Only one channel connection is
     * allowed per resource and integration.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelConnectionsControllerCreateChannelConnectionResponse create(
            @Nullable String idempotencyKey, @Nonnull CreateChannelConnectionRequestDto body,
            @Nullable Options options) {
        ChannelConnectionsControllerCreateChannelConnectionRequest request = new ChannelConnectionsControllerCreateChannelConnectionRequest(idempotencyKey, body);
        RequestOperation<ChannelConnectionsControllerCreateChannelConnectionRequest, ChannelConnectionsControllerCreateChannelConnectionResponse> operation
              = new ChannelConnectionsControllerCreateChannelConnection.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a channel connection
     * 
     * <p>Retrieve a specific channel connection by its unique identifier.
     * 
     * @return The call builder
     */
    public ChannelConnectionsControllerGetChannelConnectionByIdentifierRequestBuilder get() {
        return new ChannelConnectionsControllerGetChannelConnectionByIdentifierRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a channel connection
     * 
     * <p>Retrieve a specific channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelConnectionsControllerGetChannelConnectionByIdentifierResponse get(@Nonnull String identifier) {
        return get(identifier, null, null);
    }

    /**
     * Retrieve a channel connection
     * 
     * <p>Retrieve a specific channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelConnectionsControllerGetChannelConnectionByIdentifierResponse get(
            @Nonnull String identifier, @Nullable String idempotencyKey,
            @Nullable Options options) {
        ChannelConnectionsControllerGetChannelConnectionByIdentifierRequest request = new ChannelConnectionsControllerGetChannelConnectionByIdentifierRequest(identifier, idempotencyKey);
        RequestOperation<ChannelConnectionsControllerGetChannelConnectionByIdentifierRequest, ChannelConnectionsControllerGetChannelConnectionByIdentifierResponse> operation
              = new ChannelConnectionsControllerGetChannelConnectionByIdentifier.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a channel connection
     * 
     * <p>Update an existing channel connection by its unique identifier.
     * 
     * @return The call builder
     */
    public ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder update() {
        return new ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a channel connection
     * 
     * <p>Update an existing channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelConnectionsControllerUpdateChannelConnectionResponse update(@Nonnull String identifier, @Nonnull UpdateChannelConnectionRequestDto body) {
        return update(identifier, null, body,
            null);
    }

    /**
     * Update a channel connection
     * 
     * <p>Update an existing channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelConnectionsControllerUpdateChannelConnectionResponse update(
            @Nonnull String identifier, @Nullable String idempotencyKey,
            @Nonnull UpdateChannelConnectionRequestDto body, @Nullable Options options) {
        ChannelConnectionsControllerUpdateChannelConnectionRequest request = new ChannelConnectionsControllerUpdateChannelConnectionRequest(identifier, idempotencyKey, body);
        RequestOperation<ChannelConnectionsControllerUpdateChannelConnectionRequest, ChannelConnectionsControllerUpdateChannelConnectionResponse> operation
              = new ChannelConnectionsControllerUpdateChannelConnection.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete a channel connection
     * 
     * <p>Delete a specific channel connection by its unique identifier.
     * 
     * @return The call builder
     */
    public ChannelConnectionsControllerDeleteChannelConnectionRequestBuilder delete() {
        return new ChannelConnectionsControllerDeleteChannelConnectionRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a channel connection
     * 
     * <p>Delete a specific channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelConnectionsControllerDeleteChannelConnectionResponse delete(@Nonnull String identifier) {
        return delete(identifier, null, null);
    }

    /**
     * Delete a channel connection
     * 
     * <p>Delete a specific channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ChannelConnectionsControllerDeleteChannelConnectionResponse delete(
            @Nonnull String identifier, @Nullable String idempotencyKey,
            @Nullable Options options) {
        ChannelConnectionsControllerDeleteChannelConnectionRequest request = new ChannelConnectionsControllerDeleteChannelConnectionRequest(identifier, idempotencyKey);
        RequestOperation<ChannelConnectionsControllerDeleteChannelConnectionRequest, ChannelConnectionsControllerDeleteChannelConnectionResponse> operation
              = new ChannelConnectionsControllerDeleteChannelConnection.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
