/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.models.operations.SubscribersV1ControllerDeleteSubscriberCredentialsRequest;
import org.openapis.openapi.models.operations.SubscribersV1ControllerDeleteSubscriberCredentialsRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersV1ControllerDeleteSubscriberCredentialsResponse;
import org.openapis.openapi.operations.SubscribersV1ControllerDeleteSubscriberCredentials;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class Credentials {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncCredentials asyncSDK;

    Credentials(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncCredentials(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncCredentials async() {
        return asyncSDK;
    }

    /**
     * Delete provider credentials
     * 
     * <p>Delete subscriber credentials for a provider such as **slack** and **FCM** by **providerId**.
     * This action is irreversible and will remove the credentials for the provider for particular
     * **subscriberId**.
     * 
     * @return The call builder
     */
    public SubscribersV1ControllerDeleteSubscriberCredentialsRequestBuilder delete() {
        return new SubscribersV1ControllerDeleteSubscriberCredentialsRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete provider credentials
     * 
     * <p>Delete subscriber credentials for a provider such as **slack** and **FCM** by **providerId**.
     * This action is irreversible and will remove the credentials for the provider for particular
     * **subscriberId**.
     * 
     * @param subscriberId 
     * @param providerId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerDeleteSubscriberCredentialsResponse delete(@Nonnull String subscriberId, @Nonnull String providerId) {
        return delete(subscriberId, providerId, null,
            null);
    }

    /**
     * Delete provider credentials
     * 
     * <p>Delete subscriber credentials for a provider such as **slack** and **FCM** by **providerId**.
     * This action is irreversible and will remove the credentials for the provider for particular
     * **subscriberId**.
     * 
     * @param subscriberId 
     * @param providerId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerDeleteSubscriberCredentialsResponse delete(
            @Nonnull String subscriberId, @Nonnull String providerId,
            @Nullable String idempotencyKey, @Nullable Options options) {
        SubscribersV1ControllerDeleteSubscriberCredentialsRequest request = new SubscribersV1ControllerDeleteSubscriberCredentialsRequest(subscriberId, providerId, idempotencyKey);
        RequestOperation<SubscribersV1ControllerDeleteSubscriberCredentialsRequest, SubscribersV1ControllerDeleteSubscriberCredentialsResponse> operation
              = new SubscribersV1ControllerDeleteSubscriberCredentials.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
