/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.models.components.CreateEnvironmentRequestDto;
import org.openapis.openapi.models.components.UpdateEnvironmentRequestDto;
import org.openapis.openapi.models.operations.EnvironmentsControllerGetEnvironmentTagsRequest;
import org.openapis.openapi.models.operations.EnvironmentsControllerGetEnvironmentTagsRequestBuilder;
import org.openapis.openapi.models.operations.EnvironmentsControllerGetEnvironmentTagsResponse;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1CreateEnvironmentRequest;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1CreateEnvironmentRequestBuilder;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1CreateEnvironmentResponse;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1DeleteEnvironmentRequest;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1DeleteEnvironmentRequestBuilder;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1DeleteEnvironmentResponse;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1ListMyEnvironmentsRequest;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1ListMyEnvironmentsRequestBuilder;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1ListMyEnvironmentsResponse;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1UpdateMyEnvironmentRequest;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1UpdateMyEnvironmentRequestBuilder;
import org.openapis.openapi.models.operations.EnvironmentsControllerV1UpdateMyEnvironmentResponse;
import org.openapis.openapi.operations.EnvironmentsControllerGetEnvironmentTags;
import org.openapis.openapi.operations.EnvironmentsControllerV1CreateEnvironment;
import org.openapis.openapi.operations.EnvironmentsControllerV1DeleteEnvironment;
import org.openapis.openapi.operations.EnvironmentsControllerV1ListMyEnvironments;
import org.openapis.openapi.operations.EnvironmentsControllerV1UpdateMyEnvironment;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;

/**
 * Environments allow you to manage different stages of your application development lifecycle. Each
 * environment has its own set of API keys and configurations, enabling you to separate development,
 * staging, and production workflows.
 * 
 * <p><a href="https://docs.novu.co/platform/environments">https://docs.novu.co/platform/environments</a>
 */
public class Environments {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncEnvironments asyncSDK;

    Environments(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncEnvironments(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncEnvironments async() {
        return asyncSDK;
    }

    /**
     * Get environment tags
     * 
     * <p>Retrieve all unique tags used in workflows within the specified environment. These tags can be used
     * for filtering workflows.
     * 
     * @return The call builder
     */
    public EnvironmentsControllerGetEnvironmentTagsRequestBuilder getTags() {
        return new EnvironmentsControllerGetEnvironmentTagsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get environment tags
     * 
     * <p>Retrieve all unique tags used in workflows within the specified environment. These tags can be used
     * for filtering workflows.
     * 
     * @param environmentId Environment internal ID (MongoDB ObjectId) or identifier
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EnvironmentsControllerGetEnvironmentTagsResponse getTags(@Nonnull String environmentId) {
        return getTags(environmentId, null, null);
    }

    /**
     * Get environment tags
     * 
     * <p>Retrieve all unique tags used in workflows within the specified environment. These tags can be used
     * for filtering workflows.
     * 
     * @param environmentId Environment internal ID (MongoDB ObjectId) or identifier
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EnvironmentsControllerGetEnvironmentTagsResponse getTags(
            @Nonnull String environmentId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        EnvironmentsControllerGetEnvironmentTagsRequest request = new EnvironmentsControllerGetEnvironmentTagsRequest(environmentId, idempotencyKey);
        RequestOperation<EnvironmentsControllerGetEnvironmentTagsRequest, EnvironmentsControllerGetEnvironmentTagsResponse> operation
              = new EnvironmentsControllerGetEnvironmentTags.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create an environment
     * 
     * <p>Creates a new environment within the current organization.
     * Environments allow you to manage different stages of your application development lifecycle.
     * Each environment has its own set of API keys and configurations.
     * 
     * @return The call builder
     */
    public EnvironmentsControllerV1CreateEnvironmentRequestBuilder create() {
        return new EnvironmentsControllerV1CreateEnvironmentRequestBuilder(sdkConfiguration);
    }

    /**
     * Create an environment
     * 
     * <p>Creates a new environment within the current organization.
     * Environments allow you to manage different stages of your application development lifecycle.
     * Each environment has its own set of API keys and configurations.
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EnvironmentsControllerV1CreateEnvironmentResponse create(@Nonnull CreateEnvironmentRequestDto body) {
        return create(null, body, null);
    }

    /**
     * Create an environment
     * 
     * <p>Creates a new environment within the current organization.
     * Environments allow you to manage different stages of your application development lifecycle.
     * Each environment has its own set of API keys and configurations.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EnvironmentsControllerV1CreateEnvironmentResponse create(
            @Nullable String idempotencyKey, @Nonnull CreateEnvironmentRequestDto body,
            @Nullable Options options) {
        EnvironmentsControllerV1CreateEnvironmentRequest request = new EnvironmentsControllerV1CreateEnvironmentRequest(idempotencyKey, body);
        RequestOperation<EnvironmentsControllerV1CreateEnvironmentRequest, EnvironmentsControllerV1CreateEnvironmentResponse> operation
              = new EnvironmentsControllerV1CreateEnvironment.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List all environments
     * 
     * <p>This API returns a list of environments for the current organization.
     * Each environment contains its configuration, API keys (if user has access), and metadata.
     * 
     * @return The call builder
     */
    public EnvironmentsControllerV1ListMyEnvironmentsRequestBuilder list() {
        return new EnvironmentsControllerV1ListMyEnvironmentsRequestBuilder(sdkConfiguration);
    }

    /**
     * List all environments
     * 
     * <p>This API returns a list of environments for the current organization.
     * Each environment contains its configuration, API keys (if user has access), and metadata.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EnvironmentsControllerV1ListMyEnvironmentsResponse listDirect() {
        return list(null, null);
    }

    /**
     * List all environments
     * 
     * <p>This API returns a list of environments for the current organization.
     * Each environment contains its configuration, API keys (if user has access), and metadata.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EnvironmentsControllerV1ListMyEnvironmentsResponse list(@Nullable String idempotencyKey, @Nullable Options options) {
        EnvironmentsControllerV1ListMyEnvironmentsRequest request = new EnvironmentsControllerV1ListMyEnvironmentsRequest(idempotencyKey);
        RequestOperation<EnvironmentsControllerV1ListMyEnvironmentsRequest, EnvironmentsControllerV1ListMyEnvironmentsResponse> operation
              = new EnvironmentsControllerV1ListMyEnvironments.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update an environment
     * 
     * <p>Update an environment by its unique identifier **environmentId**.
     * You can modify the environment name, identifier, color, and other configuration settings.
     * 
     * @return The call builder
     */
    public EnvironmentsControllerV1UpdateMyEnvironmentRequestBuilder update() {
        return new EnvironmentsControllerV1UpdateMyEnvironmentRequestBuilder(sdkConfiguration);
    }

    /**
     * Update an environment
     * 
     * <p>Update an environment by its unique identifier **environmentId**.
     * You can modify the environment name, identifier, color, and other configuration settings.
     * 
     * @param environmentId The unique identifier of the environment
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EnvironmentsControllerV1UpdateMyEnvironmentResponse update(@Nonnull String environmentId, @Nonnull UpdateEnvironmentRequestDto body) {
        return update(environmentId, null, body,
            null);
    }

    /**
     * Update an environment
     * 
     * <p>Update an environment by its unique identifier **environmentId**.
     * You can modify the environment name, identifier, color, and other configuration settings.
     * 
     * @param environmentId The unique identifier of the environment
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EnvironmentsControllerV1UpdateMyEnvironmentResponse update(
            @Nonnull String environmentId, @Nullable String idempotencyKey,
            @Nonnull UpdateEnvironmentRequestDto body, @Nullable Options options) {
        EnvironmentsControllerV1UpdateMyEnvironmentRequest request = new EnvironmentsControllerV1UpdateMyEnvironmentRequest(environmentId, idempotencyKey, body);
        RequestOperation<EnvironmentsControllerV1UpdateMyEnvironmentRequest, EnvironmentsControllerV1UpdateMyEnvironmentResponse> operation
              = new EnvironmentsControllerV1UpdateMyEnvironment.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete an environment
     * 
     * <p>Delete an environment by its unique identifier **environmentId**.
     * This action is irreversible and will remove the environment and all its associated data.
     * 
     * @return The call builder
     */
    public EnvironmentsControllerV1DeleteEnvironmentRequestBuilder delete() {
        return new EnvironmentsControllerV1DeleteEnvironmentRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete an environment
     * 
     * <p>Delete an environment by its unique identifier **environmentId**.
     * This action is irreversible and will remove the environment and all its associated data.
     * 
     * @param environmentId The unique identifier of the environment
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EnvironmentsControllerV1DeleteEnvironmentResponse delete(@Nonnull String environmentId) {
        return delete(environmentId, null, null);
    }

    /**
     * Delete an environment
     * 
     * <p>Delete an environment by its unique identifier **environmentId**.
     * This action is irreversible and will remove the environment and all its associated data.
     * 
     * @param environmentId The unique identifier of the environment
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EnvironmentsControllerV1DeleteEnvironmentResponse delete(
            @Nonnull String environmentId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        EnvironmentsControllerV1DeleteEnvironmentRequest request = new EnvironmentsControllerV1DeleteEnvironmentRequest(environmentId, idempotencyKey);
        RequestOperation<EnvironmentsControllerV1DeleteEnvironmentRequest, EnvironmentsControllerV1DeleteEnvironmentResponse> operation
              = new EnvironmentsControllerV1DeleteEnvironment.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
