/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.models.components.CreateIntegrationRequestDto;
import org.openapis.openapi.models.components.GenerateChatOauthUrlRequestDto;
import org.openapis.openapi.models.components.UpdateIntegrationRequestDto;
import org.openapis.openapi.models.operations.IntegrationsControllerAutoConfigureIntegrationRequest;
import org.openapis.openapi.models.operations.IntegrationsControllerAutoConfigureIntegrationRequestBuilder;
import org.openapis.openapi.models.operations.IntegrationsControllerAutoConfigureIntegrationResponse;
import org.openapis.openapi.models.operations.IntegrationsControllerCreateIntegrationRequest;
import org.openapis.openapi.models.operations.IntegrationsControllerCreateIntegrationRequestBuilder;
import org.openapis.openapi.models.operations.IntegrationsControllerCreateIntegrationResponse;
import org.openapis.openapi.models.operations.IntegrationsControllerGetActiveIntegrationsRequest;
import org.openapis.openapi.models.operations.IntegrationsControllerGetActiveIntegrationsRequestBuilder;
import org.openapis.openapi.models.operations.IntegrationsControllerGetActiveIntegrationsResponse;
import org.openapis.openapi.models.operations.IntegrationsControllerGetChatOAuthUrlRequest;
import org.openapis.openapi.models.operations.IntegrationsControllerGetChatOAuthUrlRequestBuilder;
import org.openapis.openapi.models.operations.IntegrationsControllerGetChatOAuthUrlResponse;
import org.openapis.openapi.models.operations.IntegrationsControllerListIntegrationsRequest;
import org.openapis.openapi.models.operations.IntegrationsControllerListIntegrationsRequestBuilder;
import org.openapis.openapi.models.operations.IntegrationsControllerListIntegrationsResponse;
import org.openapis.openapi.models.operations.IntegrationsControllerRemoveIntegrationRequest;
import org.openapis.openapi.models.operations.IntegrationsControllerRemoveIntegrationRequestBuilder;
import org.openapis.openapi.models.operations.IntegrationsControllerRemoveIntegrationResponse;
import org.openapis.openapi.models.operations.IntegrationsControllerSetIntegrationAsPrimaryRequest;
import org.openapis.openapi.models.operations.IntegrationsControllerSetIntegrationAsPrimaryRequestBuilder;
import org.openapis.openapi.models.operations.IntegrationsControllerSetIntegrationAsPrimaryResponse;
import org.openapis.openapi.models.operations.IntegrationsControllerUpdateIntegrationByIdRequest;
import org.openapis.openapi.models.operations.IntegrationsControllerUpdateIntegrationByIdRequestBuilder;
import org.openapis.openapi.models.operations.IntegrationsControllerUpdateIntegrationByIdResponse;
import org.openapis.openapi.operations.IntegrationsControllerAutoConfigureIntegration;
import org.openapis.openapi.operations.IntegrationsControllerCreateIntegration;
import org.openapis.openapi.operations.IntegrationsControllerGetActiveIntegrations;
import org.openapis.openapi.operations.IntegrationsControllerGetChatOAuthUrl;
import org.openapis.openapi.operations.IntegrationsControllerListIntegrations;
import org.openapis.openapi.operations.IntegrationsControllerRemoveIntegration;
import org.openapis.openapi.operations.IntegrationsControllerSetIntegrationAsPrimary;
import org.openapis.openapi.operations.IntegrationsControllerUpdateIntegrationById;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;

/**
 * With the help of the Integration Store, you can easily integrate your favorite delivery provider.
 * During the runtime of the API, the Integrations Store is responsible for storing the configurations
 * of all the providers.
 * 
 * <p><a href="https://docs.novu.co/platform/integrations/overview">https://docs.novu.co/platform/integrations/overview</a>
 */
public class Integrations {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncIntegrations asyncSDK;

    Integrations(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncIntegrations(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncIntegrations async() {
        return asyncSDK;
    }

    /**
     * List all integrations
     * 
     * <p>List all the channels integrations created in the organization
     * 
     * @return The call builder
     */
    public IntegrationsControllerListIntegrationsRequestBuilder list() {
        return new IntegrationsControllerListIntegrationsRequestBuilder(sdkConfiguration);
    }

    /**
     * List all integrations
     * 
     * <p>List all the channels integrations created in the organization
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerListIntegrationsResponse listDirect() {
        return list(null, null);
    }

    /**
     * List all integrations
     * 
     * <p>List all the channels integrations created in the organization
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerListIntegrationsResponse list(@Nullable String idempotencyKey, @Nullable Options options) {
        IntegrationsControllerListIntegrationsRequest request = new IntegrationsControllerListIntegrationsRequest(idempotencyKey);
        RequestOperation<IntegrationsControllerListIntegrationsRequest, IntegrationsControllerListIntegrationsResponse> operation
              = new IntegrationsControllerListIntegrations.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create an integration
     * 
     * <p>Create an integration for the current environment the user is based on the API key provided.
     * Each provider supports different credentials, check the provider documentation for more details.
     * 
     * @return The call builder
     */
    public IntegrationsControllerCreateIntegrationRequestBuilder create() {
        return new IntegrationsControllerCreateIntegrationRequestBuilder(sdkConfiguration);
    }

    /**
     * Create an integration
     * 
     * <p>Create an integration for the current environment the user is based on the API key provided.
     * Each provider supports different credentials, check the provider documentation for more details.
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerCreateIntegrationResponse create(@Nonnull CreateIntegrationRequestDto body) {
        return create(null, body, null);
    }

    /**
     * Create an integration
     * 
     * <p>Create an integration for the current environment the user is based on the API key provided.
     * Each provider supports different credentials, check the provider documentation for more details.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerCreateIntegrationResponse create(
            @Nullable String idempotencyKey, @Nonnull CreateIntegrationRequestDto body,
            @Nullable Options options) {
        IntegrationsControllerCreateIntegrationRequest request = new IntegrationsControllerCreateIntegrationRequest(idempotencyKey, body);
        RequestOperation<IntegrationsControllerCreateIntegrationRequest, IntegrationsControllerCreateIntegrationResponse> operation
              = new IntegrationsControllerCreateIntegration.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update an integration
     * 
     * <p>Update an integration by its unique key identifier **integrationId**.
     * Each provider supports different credentials, check the provider documentation for more details.
     * 
     * @return The call builder
     */
    public IntegrationsControllerUpdateIntegrationByIdRequestBuilder update() {
        return new IntegrationsControllerUpdateIntegrationByIdRequestBuilder(sdkConfiguration);
    }

    /**
     * Update an integration
     * 
     * <p>Update an integration by its unique key identifier **integrationId**.
     * Each provider supports different credentials, check the provider documentation for more details.
     * 
     * @param integrationId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerUpdateIntegrationByIdResponse update(@Nonnull String integrationId, @Nonnull UpdateIntegrationRequestDto body) {
        return update(integrationId, null, body,
            null);
    }

    /**
     * Update an integration
     * 
     * <p>Update an integration by its unique key identifier **integrationId**.
     * Each provider supports different credentials, check the provider documentation for more details.
     * 
     * @param integrationId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerUpdateIntegrationByIdResponse update(
            @Nonnull String integrationId, @Nullable String idempotencyKey,
            @Nonnull UpdateIntegrationRequestDto body, @Nullable Options options) {
        IntegrationsControllerUpdateIntegrationByIdRequest request = new IntegrationsControllerUpdateIntegrationByIdRequest(integrationId, idempotencyKey, body);
        RequestOperation<IntegrationsControllerUpdateIntegrationByIdRequest, IntegrationsControllerUpdateIntegrationByIdResponse> operation
              = new IntegrationsControllerUpdateIntegrationById.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete an integration
     * 
     * <p>Delete an integration by its unique key identifier **integrationId**.
     * This action is irreversible.
     * 
     * @return The call builder
     */
    public IntegrationsControllerRemoveIntegrationRequestBuilder delete() {
        return new IntegrationsControllerRemoveIntegrationRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete an integration
     * 
     * <p>Delete an integration by its unique key identifier **integrationId**.
     * This action is irreversible.
     * 
     * @param integrationId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerRemoveIntegrationResponse delete(@Nonnull String integrationId) {
        return delete(integrationId, null, null);
    }

    /**
     * Delete an integration
     * 
     * <p>Delete an integration by its unique key identifier **integrationId**.
     * This action is irreversible.
     * 
     * @param integrationId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerRemoveIntegrationResponse delete(
            @Nonnull String integrationId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        IntegrationsControllerRemoveIntegrationRequest request = new IntegrationsControllerRemoveIntegrationRequest(integrationId, idempotencyKey);
        RequestOperation<IntegrationsControllerRemoveIntegrationRequest, IntegrationsControllerRemoveIntegrationResponse> operation
              = new IntegrationsControllerRemoveIntegration.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Auto-configure an integration for inbound webhooks
     * 
     * <p>Auto-configure an integration by its unique key identifier **integrationId** for inbound webhook
     * support.
     * This will automatically generate required webhook signing keys and configure webhook endpoints.
     * 
     * @return The call builder
     */
    public IntegrationsControllerAutoConfigureIntegrationRequestBuilder autoConfigure() {
        return new IntegrationsControllerAutoConfigureIntegrationRequestBuilder(sdkConfiguration);
    }

    /**
     * Auto-configure an integration for inbound webhooks
     * 
     * <p>Auto-configure an integration by its unique key identifier **integrationId** for inbound webhook
     * support.
     * This will automatically generate required webhook signing keys and configure webhook endpoints.
     * 
     * @param integrationId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerAutoConfigureIntegrationResponse autoConfigure(@Nonnull String integrationId) {
        return autoConfigure(integrationId, null, null);
    }

    /**
     * Auto-configure an integration for inbound webhooks
     * 
     * <p>Auto-configure an integration by its unique key identifier **integrationId** for inbound webhook
     * support.
     * This will automatically generate required webhook signing keys and configure webhook endpoints.
     * 
     * @param integrationId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerAutoConfigureIntegrationResponse autoConfigure(
            @Nonnull String integrationId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        IntegrationsControllerAutoConfigureIntegrationRequest request = new IntegrationsControllerAutoConfigureIntegrationRequest(integrationId, idempotencyKey);
        RequestOperation<IntegrationsControllerAutoConfigureIntegrationRequest, IntegrationsControllerAutoConfigureIntegrationResponse> operation
              = new IntegrationsControllerAutoConfigureIntegration.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update integration as primary
     * 
     * <p>Update an integration as **primary** by its unique key identifier **integrationId**.
     * This API will set the integration as primary for that channel in the current environment.
     * Primary integration is used to deliver notification for sms and email channels in the workflow.
     * 
     * @return The call builder
     */
    public IntegrationsControllerSetIntegrationAsPrimaryRequestBuilder setPrimary() {
        return new IntegrationsControllerSetIntegrationAsPrimaryRequestBuilder(sdkConfiguration);
    }

    /**
     * Update integration as primary
     * 
     * <p>Update an integration as **primary** by its unique key identifier **integrationId**.
     * This API will set the integration as primary for that channel in the current environment.
     * Primary integration is used to deliver notification for sms and email channels in the workflow.
     * 
     * @param integrationId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerSetIntegrationAsPrimaryResponse setPrimary(@Nonnull String integrationId) {
        return setPrimary(integrationId, null, null);
    }

    /**
     * Update integration as primary
     * 
     * <p>Update an integration as **primary** by its unique key identifier **integrationId**.
     * This API will set the integration as primary for that channel in the current environment.
     * Primary integration is used to deliver notification for sms and email channels in the workflow.
     * 
     * @param integrationId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerSetIntegrationAsPrimaryResponse setPrimary(
            @Nonnull String integrationId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        IntegrationsControllerSetIntegrationAsPrimaryRequest request = new IntegrationsControllerSetIntegrationAsPrimaryRequest(integrationId, idempotencyKey);
        RequestOperation<IntegrationsControllerSetIntegrationAsPrimaryRequest, IntegrationsControllerSetIntegrationAsPrimaryResponse> operation
              = new IntegrationsControllerSetIntegrationAsPrimary.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List active integrations
     * 
     * <p>List all the active integrations created in the organization
     * 
     * @return The call builder
     */
    public IntegrationsControllerGetActiveIntegrationsRequestBuilder listActive() {
        return new IntegrationsControllerGetActiveIntegrationsRequestBuilder(sdkConfiguration);
    }

    /**
     * List active integrations
     * 
     * <p>List all the active integrations created in the organization
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerGetActiveIntegrationsResponse listActiveDirect() {
        return listActive(null, null);
    }

    /**
     * List active integrations
     * 
     * <p>List all the active integrations created in the organization
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerGetActiveIntegrationsResponse listActive(@Nullable String idempotencyKey, @Nullable Options options) {
        IntegrationsControllerGetActiveIntegrationsRequest request = new IntegrationsControllerGetActiveIntegrationsRequest(idempotencyKey);
        RequestOperation<IntegrationsControllerGetActiveIntegrationsRequest, IntegrationsControllerGetActiveIntegrationsResponse> operation
              = new IntegrationsControllerGetActiveIntegrations.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Generate chat OAuth URL
     * 
     * <p>Generate an OAuth URL for chat integrations like Slack and MS Teams.
     * This URL allows subscribers to authorize the integration, enabling the system to send messages
     * through their chat workspace. The generated URL expires after 5 minutes.
     * 
     * @return The call builder
     */
    public IntegrationsControllerGetChatOAuthUrlRequestBuilder generateChatOAuth() {
        return new IntegrationsControllerGetChatOAuthUrlRequestBuilder(sdkConfiguration);
    }

    /**
     * Generate chat OAuth URL
     * 
     * <p>Generate an OAuth URL for chat integrations like Slack and MS Teams.
     * This URL allows subscribers to authorize the integration, enabling the system to send messages
     * through their chat workspace. The generated URL expires after 5 minutes.
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerGetChatOAuthUrlResponse generateChatOAuth(@Nonnull GenerateChatOauthUrlRequestDto body) {
        return generateChatOAuth(null, body, null);
    }

    /**
     * Generate chat OAuth URL
     * 
     * <p>Generate an OAuth URL for chat integrations like Slack and MS Teams.
     * This URL allows subscribers to authorize the integration, enabling the system to send messages
     * through their chat workspace. The generated URL expires after 5 minutes.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public IntegrationsControllerGetChatOAuthUrlResponse generateChatOAuth(
            @Nullable String idempotencyKey, @Nonnull GenerateChatOauthUrlRequestDto body,
            @Nullable Options options) {
        IntegrationsControllerGetChatOAuthUrlRequest request = new IntegrationsControllerGetChatOAuthUrlRequest(idempotencyKey, body);
        RequestOperation<IntegrationsControllerGetChatOAuthUrlRequest, IntegrationsControllerGetChatOAuthUrlResponse> operation
              = new IntegrationsControllerGetChatOAuthUrl.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
