/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import java.util.function.Consumer;
import org.openapis.openapi.models.components.BulkTriggerEventDto;
import org.openapis.openapi.models.components.TriggerEventRequestDto;
import org.openapis.openapi.models.components.TriggerEventToAllRequestDto;
import org.openapis.openapi.models.operations.EventsControllerBroadcastEventToAllRequest;
import org.openapis.openapi.models.operations.EventsControllerBroadcastEventToAllRequestBuilder;
import org.openapis.openapi.models.operations.EventsControllerBroadcastEventToAllResponse;
import org.openapis.openapi.models.operations.EventsControllerCancelRequest;
import org.openapis.openapi.models.operations.EventsControllerCancelRequestBuilder;
import org.openapis.openapi.models.operations.EventsControllerCancelResponse;
import org.openapis.openapi.models.operations.EventsControllerTriggerBulkRequest;
import org.openapis.openapi.models.operations.EventsControllerTriggerBulkRequestBuilder;
import org.openapis.openapi.models.operations.EventsControllerTriggerBulkResponse;
import org.openapis.openapi.models.operations.EventsControllerTriggerRequest;
import org.openapis.openapi.models.operations.EventsControllerTriggerRequestBuilder;
import org.openapis.openapi.models.operations.EventsControllerTriggerResponse;
import org.openapis.openapi.operations.EventsControllerBroadcastEventToAll;
import org.openapis.openapi.operations.EventsControllerCancel;
import org.openapis.openapi.operations.EventsControllerTrigger;
import org.openapis.openapi.operations.EventsControllerTriggerBulk;
import org.openapis.openapi.utils.HTTPClient;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.SpeakeasyHTTPClient;
import org.openapis.openapi.utils.Utils;

/**
 * Novu API: Novu REST API. Please see https://docs.novu.co/api-reference for more details.
 * 
 * <p><a href="https://docs.novu.co">Novu Documentation</a>
 */
public class Novu {
    private static final Headers _headers = Headers.EMPTY;


    /**
     * SERVERS contains the list of server urls available to the SDK.
     */
    public static final String[] SERVERS = {

        "https://api.novu.co",

        "https://eu.api.novu.co",
    };


    private final Contexts contexts;

    /**
     * Environments allow you to manage different stages of your application development lifecycle. Each
     * environment has its own set of API keys and configurations, enabling you to separate development,
     * staging, and production workflows.
     * 
     * <p><a href="https://docs.novu.co/platform/environments">https://docs.novu.co/platform/environments</a>
     */
    private final Environments environments;


    private final Activity activity;

    /**
     * Layouts are reusable wrappers for your email notifications.
     * 
     * <p><a href="https://docs.novu.co/platform/workflow/layouts">https://docs.novu.co/platform/workflow/layouts</a>
     */
    private final Layouts layouts;


    private final Subscribers subscribers;


    private final SubscribersPreferences subscribersPreferences;


    private final Topics topics;


    private final TopicsSubscriptions topicsSubscriptions;


    private final Translations translations;


    private final TranslationsMaster translationsMaster;


    private final Workflows workflows;


    private final ChannelConnections channelConnections;


    private final ChannelEndpoints channelEndpoints;

    /**
     * With the help of the Integration Store, you can easily integrate your favorite delivery provider.
     * During the runtime of the API, the Integrations Store is responsible for storing the configurations
     * of all the providers.
     * 
     * <p><a href="https://docs.novu.co/platform/integrations/overview">https://docs.novu.co/platform/integrations/overview</a>
     */
    private final Integrations integrations;

    /**
     * A message in Novu represents a notification delivered to a recipient on a particular channel.
     * Messages contain information about the request that triggered its delivery, a view of the data sent
     * to the recipient, and a timeline of its lifecycle events. Learn more about messages.
     * 
     * <p><a href="https://docs.novu.co/workflows/messages">https://docs.novu.co/workflows/messages</a>
     */
    private final Messages messages;


    private final Notifications notifications;


    private final SubscribersMessages1 subscribersMessages;


    private final SubscribersNotifications subscribersNotifications;


    public Contexts contexts() {
        return contexts;
    }

    /**
     * Environments allow you to manage different stages of your application development lifecycle. Each
     * environment has its own set of API keys and configurations, enabling you to separate development,
     * staging, and production workflows.
     * 
     * <p><a href="https://docs.novu.co/platform/environments">https://docs.novu.co/platform/environments</a>
     */
    public Environments environments() {
        return environments;
    }


    public Activity activity() {
        return activity;
    }

    /**
     * Layouts are reusable wrappers for your email notifications.
     * 
     * <p><a href="https://docs.novu.co/platform/workflow/layouts">https://docs.novu.co/platform/workflow/layouts</a>
     */
    public Layouts layouts() {
        return layouts;
    }


    public Subscribers subscribers() {
        return subscribers;
    }


    public SubscribersPreferences subscribersPreferences() {
        return subscribersPreferences;
    }


    public Topics topics() {
        return topics;
    }


    public TopicsSubscriptions topicsSubscriptions() {
        return topicsSubscriptions;
    }


    public Translations translations() {
        return translations;
    }


    public TranslationsMaster translationsMaster() {
        return translationsMaster;
    }


    public Workflows workflows() {
        return workflows;
    }


    public ChannelConnections channelConnections() {
        return channelConnections;
    }


    public ChannelEndpoints channelEndpoints() {
        return channelEndpoints;
    }

    /**
     * With the help of the Integration Store, you can easily integrate your favorite delivery provider.
     * During the runtime of the API, the Integrations Store is responsible for storing the configurations
     * of all the providers.
     * 
     * <p><a href="https://docs.novu.co/platform/integrations/overview">https://docs.novu.co/platform/integrations/overview</a>
     */
    public Integrations integrations() {
        return integrations;
    }

    /**
     * A message in Novu represents a notification delivered to a recipient on a particular channel.
     * Messages contain information about the request that triggered its delivery, a view of the data sent
     * to the recipient, and a timeline of its lifecycle events. Learn more about messages.
     * 
     * <p><a href="https://docs.novu.co/workflows/messages">https://docs.novu.co/workflows/messages</a>
     */
    public Messages messages() {
        return messages;
    }


    public Notifications notifications() {
        return notifications;
    }


    public SubscribersMessages1 subscribersMessages() {
        return subscribersMessages;
    }


    public SubscribersNotifications subscribersNotifications() {
        return subscribersNotifications;
    }private SDKConfiguration sdkConfiguration;
    private final AsyncNovu asyncSDK;

    /**
     * The Builder class allows the configuration of a new instance of the SDK.
     */
    public static class Builder {

        private final SDKConfiguration sdkConfiguration = new SDKConfiguration();
        private String serverUrl;
        private String server;
        

        private Builder() {
        }

        /**
         * Allows the default HTTP client to be overridden with a custom implementation.
         *
         * @param client The HTTP client to use for all requests.
         * @return The builder instance.
         */
        public Builder client(HTTPClient client) {
            this.sdkConfiguration.setClient(client);
            return this;
        }
        /**
         * Configures the SDK security to use the provided secret.
         *
         * @param secretKey The secret to use for all requests.
         * @return The builder instance.
         */
        public Builder secretKey(String secretKey) {
            this.sdkConfiguration.setSecuritySource(SecuritySource.of(org.openapis.openapi.models.components.Security.builder()
              .secretKey(secretKey)
              .build()));
            return this;
        }

        /**
         * Configures the SDK to use a custom security source.
         *
         * @param securitySource The security source to use for all requests.
         * @return The builder instance.
         */
        public Builder securitySource(SecuritySource securitySource) {
            Utils.checkNotNull(securitySource, "securitySource");
            this.sdkConfiguration.setSecuritySource(securitySource);
            return this;
        }
        
        /**
         * Overrides the default server URL.
         *
         * @param serverUrl The server URL to use for all requests.
         * @return The builder instance.
         */
        public Builder serverURL(String serverUrl) {
            this.serverUrl = serverUrl;
            return this;
        }

        /**
         * Overrides the default server URL with a templated URL populated with the provided parameters.
         *
         * @param serverUrl The server URL to use for all requests.
         * @param params The parameters to use when templating the URL.
         * @return The builder instance.
         */
        public Builder serverURL(String serverUrl, Map<String, String> params) {
            this.serverUrl = Utils.templateUrl(serverUrl, params);
            return this;
        }
        
        /**
         * Overrides the default server by index.
         *
         * @param serverIdx The server to use for all requests.
         * @return The builder instance.
         */
        public Builder serverIndex(int serverIdx) {
            this.sdkConfiguration.setServerIdx(serverIdx);
            this.serverUrl= SERVERS[serverIdx];
            return this;
        }
        
        /**
         * Overrides the default configuration for retries
         *
         * @param retryConfig The retry configuration to use for all requests.
         * @return The builder instance.
         */
        public Builder retryConfig(RetryConfig retryConfig) {
            this.sdkConfiguration.setRetryConfig(Optional.of(retryConfig));
            return this;
        }

        /**
         * Enables debug logging for HTTP requests and responses, including JSON body content.
         * <p>
         * Convenience method that calls {@link HTTPClient#enableDebugLogging(boolean)}.
         * {@link SpeakeasyHTTPClient} honors this setting. If you are using a custom HTTP client,
         * it is up to the custom client to honor this setting.
         * </p>
         *
         * @param enabled Whether to enable debug logging.
         * @return The builder instance.
         */
        public Builder enableHTTPDebugLogging(boolean enabled) {
            this.sdkConfiguration.client().enableDebugLogging(enabled);
            return this;
        }

        // Visible for testing, may be accessed via reflection in tests
        Builder _hooks(org.openapis.openapi.utils.Hooks hooks) {
            sdkConfiguration.setHooks(hooks);  
            return this;  
        }
        
        // Visible for testing, may be accessed via reflection in tests
        Builder _hooks(Consumer<? super org.openapis.openapi.utils.Hooks> consumer) {
            consumer.accept(sdkConfiguration.hooks());
            return this;    
        }

        /**
         * Builds a new instance of the SDK.
         *
         * @return The SDK instance.
         */
        public Novu build() {
            if (serverUrl == null || serverUrl.isBlank()) {
                serverUrl = SERVERS[0];
                sdkConfiguration.setServerIdx(0);
            }
            sdkConfiguration.setServerUrl(serverUrl);
            return new Novu(sdkConfiguration);
        }
    }

    /**
     * Get a new instance of the SDK builder to configure a new instance of the SDK.
     *
     * @return The SDK builder instance.
     */
    public static Builder builder() {
        return new Builder();
    }

    public Novu(SDKConfiguration sdkConfiguration) {
        sdkConfiguration.initialize();
        this.contexts = new Contexts(sdkConfiguration);
        this.environments = new Environments(sdkConfiguration);
        this.activity = new Activity(sdkConfiguration);
        this.layouts = new Layouts(sdkConfiguration);
        this.subscribers = new Subscribers(sdkConfiguration);
        this.subscribersPreferences = new SubscribersPreferences(sdkConfiguration);
        this.topics = new Topics(sdkConfiguration);
        this.topicsSubscriptions = new TopicsSubscriptions(sdkConfiguration);
        this.translations = new Translations(sdkConfiguration);
        this.translationsMaster = new TranslationsMaster(sdkConfiguration);
        this.workflows = new Workflows(sdkConfiguration);
        this.channelConnections = new ChannelConnections(sdkConfiguration);
        this.channelEndpoints = new ChannelEndpoints(sdkConfiguration);
        this.integrations = new Integrations(sdkConfiguration);
        this.messages = new Messages(sdkConfiguration);
        this.notifications = new Notifications(sdkConfiguration);
        this.subscribersMessages = new SubscribersMessages1(sdkConfiguration);
        this.subscribersNotifications = new SubscribersNotifications(sdkConfiguration);
        sdkConfiguration = sdkConfiguration.hooks().sdkInit(sdkConfiguration);
        this.asyncSDK = new AsyncNovu(this, sdkConfiguration);
        this.sdkConfiguration = sdkConfiguration;
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncNovu async() {
        return asyncSDK;
    }

    /**
     * Trigger event
     * 
     * <p>Trigger event is the main (and only) way to send notifications to subscribers. The trigger
     * identifier is used to match the particular workflow associated with it. Maximum number of recipients
     * can be 100.
     * 
     * <p>Additional information can be passed according the body interface below.
     * To prevent duplicate triggers, you can optionally pass a **transactionId** in the request body. If
     * the same **transactionId** is used again, the trigger will be ignored. The retention period depends
     * on your billing tier.
     * 
     * @return The call builder
     */
    public EventsControllerTriggerRequestBuilder trigger() {
        return new EventsControllerTriggerRequestBuilder(sdkConfiguration);
    }

    /**
     * Trigger event
     * 
     * <p>Trigger event is the main (and only) way to send notifications to subscribers. The trigger
     * identifier is used to match the particular workflow associated with it. Maximum number of recipients
     * can be 100.
     * 
     * <p>Additional information can be passed according the body interface below.
     * To prevent duplicate triggers, you can optionally pass a **transactionId** in the request body. If
     * the same **transactionId** is used again, the trigger will be ignored. The retention period depends
     * on your billing tier.
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EventsControllerTriggerResponse trigger(@Nonnull TriggerEventRequestDto body) {
        return trigger(null, body, null);
    }

    /**
     * Trigger event
     * 
     * <p>Trigger event is the main (and only) way to send notifications to subscribers. The trigger
     * identifier is used to match the particular workflow associated with it. Maximum number of recipients
     * can be 100.
     * 
     * <p>Additional information can be passed according the body interface below.
     * To prevent duplicate triggers, you can optionally pass a **transactionId** in the request body. If
     * the same **transactionId** is used again, the trigger will be ignored. The retention period depends
     * on your billing tier.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EventsControllerTriggerResponse trigger(
            @Nullable String idempotencyKey, @Nonnull TriggerEventRequestDto body,
            @Nullable Options options) {
        EventsControllerTriggerRequest request = new EventsControllerTriggerRequest(idempotencyKey, body);
        RequestOperation<EventsControllerTriggerRequest, EventsControllerTriggerResponse> operation
              = new EventsControllerTrigger.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Cancel triggered event
     * 
     * <p>Using a previously generated transactionId during the event trigger,
     * will cancel any active or pending workflows. This is useful to cancel active digests, delays etc...
     * 
     * @return The call builder
     */
    public EventsControllerCancelRequestBuilder cancel() {
        return new EventsControllerCancelRequestBuilder(sdkConfiguration);
    }

    /**
     * Cancel triggered event
     * 
     * <p>Using a previously generated transactionId during the event trigger,
     * will cancel any active or pending workflows. This is useful to cancel active digests, delays etc...
     * 
     * @param transactionId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EventsControllerCancelResponse cancel(@Nonnull String transactionId) {
        return cancel(transactionId, null, null);
    }

    /**
     * Cancel triggered event
     * 
     * <p>Using a previously generated transactionId during the event trigger,
     * will cancel any active or pending workflows. This is useful to cancel active digests, delays etc...
     * 
     * @param transactionId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EventsControllerCancelResponse cancel(
            @Nonnull String transactionId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        EventsControllerCancelRequest request = new EventsControllerCancelRequest(transactionId, idempotencyKey);
        RequestOperation<EventsControllerCancelRequest, EventsControllerCancelResponse> operation
              = new EventsControllerCancel.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Broadcast event to all
     * 
     * <p>Trigger a broadcast event to all existing subscribers, could be used to send announcements, etc.
     * 
     * <p>In the future could be used to trigger events to a subset of subscribers based on defined filters.
     * 
     * @return The call builder
     */
    public EventsControllerBroadcastEventToAllRequestBuilder triggerBroadcast() {
        return new EventsControllerBroadcastEventToAllRequestBuilder(sdkConfiguration);
    }

    /**
     * Broadcast event to all
     * 
     * <p>Trigger a broadcast event to all existing subscribers, could be used to send announcements, etc.
     * 
     * <p>In the future could be used to trigger events to a subset of subscribers based on defined filters.
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EventsControllerBroadcastEventToAllResponse triggerBroadcast(@Nonnull TriggerEventToAllRequestDto body) {
        return triggerBroadcast(null, body, null);
    }

    /**
     * Broadcast event to all
     * 
     * <p>Trigger a broadcast event to all existing subscribers, could be used to send announcements, etc.
     * 
     * <p>In the future could be used to trigger events to a subset of subscribers based on defined filters.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EventsControllerBroadcastEventToAllResponse triggerBroadcast(
            @Nullable String idempotencyKey, @Nonnull TriggerEventToAllRequestDto body,
            @Nullable Options options) {
        EventsControllerBroadcastEventToAllRequest request = new EventsControllerBroadcastEventToAllRequest(idempotencyKey, body);
        RequestOperation<EventsControllerBroadcastEventToAllRequest, EventsControllerBroadcastEventToAllResponse> operation
              = new EventsControllerBroadcastEventToAll.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Bulk trigger event
     * 
     * <p>Using this endpoint you can trigger multiple events at once, to avoid multiple calls to the API.
     * The bulk API is limited to 100 events per request.
     * 
     * @return The call builder
     */
    public EventsControllerTriggerBulkRequestBuilder triggerBulk() {
        return new EventsControllerTriggerBulkRequestBuilder(sdkConfiguration);
    }

    /**
     * Bulk trigger event
     * 
     * <p>Using this endpoint you can trigger multiple events at once, to avoid multiple calls to the API.
     * The bulk API is limited to 100 events per request.
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EventsControllerTriggerBulkResponse triggerBulk(@Nonnull BulkTriggerEventDto body) {
        return triggerBulk(null, body, null);
    }

    /**
     * Bulk trigger event
     * 
     * <p>Using this endpoint you can trigger multiple events at once, to avoid multiple calls to the API.
     * The bulk API is limited to 100 events per request.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public EventsControllerTriggerBulkResponse triggerBulk(
            @Nullable String idempotencyKey, @Nonnull BulkTriggerEventDto body,
            @Nullable Options options) {
        EventsControllerTriggerBulkRequest request = new EventsControllerTriggerBulkRequest(idempotencyKey, body);
        RequestOperation<EventsControllerTriggerBulkRequest, EventsControllerTriggerBulkResponse> operation
              = new EventsControllerTriggerBulk.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
