/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.models.operations.Criticality;
import org.openapis.openapi.models.operations.SubscribersControllerGetSubscriberPreferencesRequest;
import org.openapis.openapi.models.operations.SubscribersControllerGetSubscriberPreferencesRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersControllerGetSubscriberPreferencesResponse;
import org.openapis.openapi.operations.SubscribersControllerGetSubscriberPreferences;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class Preferences {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncPreferences asyncSDK;

    Preferences(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncPreferences(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncPreferences async() {
        return asyncSDK;
    }

    /**
     * Retrieve subscriber preferences
     * 
     * <p>Retrieve subscriber channel preferences by its unique key identifier **subscriberId**.
     * This API returns all five channels preferences for all workflows and global preferences.
     * 
     * @return The call builder
     */
    public SubscribersControllerGetSubscriberPreferencesRequestBuilder getPreferences() {
        return new SubscribersControllerGetSubscriberPreferencesRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve subscriber preferences
     * 
     * <p>Retrieve subscriber channel preferences by its unique key identifier **subscriberId**.
     * This API returns all five channels preferences for all workflows and global preferences.
     * 
     * @param subscriberId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerGetSubscriberPreferencesResponse getPreferences(@Nonnull String subscriberId) {
        return getPreferences(subscriberId, null, null,
            null);
    }

    /**
     * Retrieve subscriber preferences
     * 
     * <p>Retrieve subscriber channel preferences by its unique key identifier **subscriberId**.
     * This API returns all five channels preferences for all workflows and global preferences.
     * 
     * @param subscriberId 
     * @param criticality 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerGetSubscriberPreferencesResponse getPreferences(
            @Nonnull String subscriberId, @Nullable Criticality criticality,
            @Nullable String idempotencyKey, @Nullable Options options) {
        SubscribersControllerGetSubscriberPreferencesRequest request = new SubscribersControllerGetSubscriberPreferencesRequest(subscriberId, criticality, idempotencyKey);
        RequestOperation<SubscribersControllerGetSubscriberPreferencesRequest, SubscribersControllerGetSubscriberPreferencesResponse> operation
              = new SubscribersControllerGetSubscriberPreferences.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
