/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import org.openapis.openapi.models.operations.SubscribersV1ControllerMarkActionAsSeenRequest;
import org.openapis.openapi.models.operations.SubscribersV1ControllerMarkActionAsSeenRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersV1ControllerMarkActionAsSeenResponse;
import org.openapis.openapi.operations.SubscribersV1ControllerMarkActionAsSeen;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class SubscribersMessages1 {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncSubscribersMessages1 asyncSDK;

    SubscribersMessages1(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncSubscribersMessages1(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncSubscribersMessages1 async() {
        return asyncSDK;
    }

    /**
     * Update notification action status
     * 
     * <p>Update in-app (inbox) notification's action status by its unique key identifier **messageId** and
     * type field **type**.
     * **type** field can be **primary** or **secondary**
     * 
     * @return The call builder
     */
    public SubscribersV1ControllerMarkActionAsSeenRequestBuilder updateAsSeen() {
        return new SubscribersV1ControllerMarkActionAsSeenRequestBuilder(sdkConfiguration);
    }

    /**
     * Update notification action status
     * 
     * <p>Update in-app (inbox) notification's action status by its unique key identifier **messageId** and
     * type field **type**.
     * **type** field can be **primary** or **secondary**
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerMarkActionAsSeenResponse updateAsSeen(@Nonnull SubscribersV1ControllerMarkActionAsSeenRequest request) {
        return updateAsSeen(request, null);
    }

    /**
     * Update notification action status
     * 
     * <p>Update in-app (inbox) notification's action status by its unique key identifier **messageId** and
     * type field **type**.
     * **type** field can be **primary** or **secondary**
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerMarkActionAsSeenResponse updateAsSeen(@Nonnull SubscribersV1ControllerMarkActionAsSeenRequest request, @Nullable Options options) {
        RequestOperation<SubscribersV1ControllerMarkActionAsSeenRequest, SubscribersV1ControllerMarkActionAsSeenResponse> operation
              = new SubscribersV1ControllerMarkActionAsSeen.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
