/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import org.openapis.openapi.models.operations.SubscribersV1ControllerGetNotificationsFeedRequest;
import org.openapis.openapi.models.operations.SubscribersV1ControllerGetNotificationsFeedRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersV1ControllerGetNotificationsFeedResponse;
import org.openapis.openapi.operations.SubscribersV1ControllerGetNotificationsFeed;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class SubscribersNotifications {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncSubscribersNotifications asyncSDK;

    SubscribersNotifications(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncSubscribersNotifications(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncSubscribersNotifications async() {
        return asyncSDK;
    }

    /**
     * Retrieve subscriber notifications
     * 
     * <p>Retrieve subscriber in-app (inbox) notifications by its unique key identifier **subscriberId**.
     * 
     * @return The call builder
     */
    public SubscribersV1ControllerGetNotificationsFeedRequestBuilder getFeed() {
        return new SubscribersV1ControllerGetNotificationsFeedRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve subscriber notifications
     * 
     * <p>Retrieve subscriber in-app (inbox) notifications by its unique key identifier **subscriberId**.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerGetNotificationsFeedResponse getFeed(@Nonnull SubscribersV1ControllerGetNotificationsFeedRequest request) {
        return getFeed(request, null);
    }

    /**
     * Retrieve subscriber notifications
     * 
     * <p>Retrieve subscriber in-app (inbox) notifications by its unique key identifier **subscriberId**.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerGetNotificationsFeedResponse getFeed(@Nonnull SubscribersV1ControllerGetNotificationsFeedRequest request, @Nullable Options options) {
        RequestOperation<SubscribersV1ControllerGetNotificationsFeedRequest, SubscribersV1ControllerGetNotificationsFeedResponse> operation
              = new SubscribersV1ControllerGetNotificationsFeed.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
