/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import org.openapis.openapi.models.components.BulkSubscriberCreateDto;
import org.openapis.openapi.models.components.CreateSubscriberRequestDto;
import org.openapis.openapi.models.components.MessageMarkAsRequestDto;
import org.openapis.openapi.models.components.PatchSubscriberPreferencesDto;
import org.openapis.openapi.models.components.PatchSubscriberRequestDto;
import org.openapis.openapi.models.components.UpdateSubscriberChannelRequestDto;
import org.openapis.openapi.models.components.UpdateSubscriberOnlineFlagRequestDto;
import org.openapis.openapi.models.operations.SubscribersControllerCreateSubscriberRequest;
import org.openapis.openapi.models.operations.SubscribersControllerCreateSubscriberRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersControllerCreateSubscriberResponse;
import org.openapis.openapi.models.operations.SubscribersControllerGetSubscriberRequest;
import org.openapis.openapi.models.operations.SubscribersControllerGetSubscriberRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersControllerGetSubscriberResponse;
import org.openapis.openapi.models.operations.SubscribersControllerPatchSubscriberRequest;
import org.openapis.openapi.models.operations.SubscribersControllerPatchSubscriberRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersControllerPatchSubscriberResponse;
import org.openapis.openapi.models.operations.SubscribersControllerRemoveSubscriberRequest;
import org.openapis.openapi.models.operations.SubscribersControllerRemoveSubscriberRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersControllerRemoveSubscriberResponse;
import org.openapis.openapi.models.operations.SubscribersControllerSearchSubscribersRequest;
import org.openapis.openapi.models.operations.SubscribersControllerSearchSubscribersRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersControllerSearchSubscribersResponse;
import org.openapis.openapi.models.operations.SubscribersControllerUpdateSubscriberPreferencesRequest;
import org.openapis.openapi.models.operations.SubscribersControllerUpdateSubscriberPreferencesRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersControllerUpdateSubscriberPreferencesResponse;
import org.openapis.openapi.models.operations.SubscribersV1ControllerBulkCreateSubscribersRequest;
import org.openapis.openapi.models.operations.SubscribersV1ControllerBulkCreateSubscribersRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersV1ControllerBulkCreateSubscribersResponse;
import org.openapis.openapi.models.operations.SubscribersV1ControllerGetUnseenCountRequest;
import org.openapis.openapi.models.operations.SubscribersV1ControllerGetUnseenCountRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersV1ControllerGetUnseenCountResponse;
import org.openapis.openapi.models.operations.SubscribersV1ControllerMarkMessagesAsRequest;
import org.openapis.openapi.models.operations.SubscribersV1ControllerMarkMessagesAsRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersV1ControllerMarkMessagesAsResponse;
import org.openapis.openapi.models.operations.SubscribersV1ControllerModifySubscriberChannelRequest;
import org.openapis.openapi.models.operations.SubscribersV1ControllerModifySubscriberChannelRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersV1ControllerModifySubscriberChannelResponse;
import org.openapis.openapi.models.operations.SubscribersV1ControllerUpdateSubscriberChannelRequest;
import org.openapis.openapi.models.operations.SubscribersV1ControllerUpdateSubscriberChannelRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersV1ControllerUpdateSubscriberChannelResponse;
import org.openapis.openapi.models.operations.SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest;
import org.openapis.openapi.models.operations.SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse;
import org.openapis.openapi.operations.SubscribersControllerCreateSubscriber;
import org.openapis.openapi.operations.SubscribersControllerGetSubscriber;
import org.openapis.openapi.operations.SubscribersControllerPatchSubscriber;
import org.openapis.openapi.operations.SubscribersControllerRemoveSubscriber;
import org.openapis.openapi.operations.SubscribersControllerSearchSubscribers;
import org.openapis.openapi.operations.SubscribersControllerUpdateSubscriberPreferences;
import org.openapis.openapi.operations.SubscribersV1ControllerBulkCreateSubscribers;
import org.openapis.openapi.operations.SubscribersV1ControllerGetUnseenCount;
import org.openapis.openapi.operations.SubscribersV1ControllerMarkMessagesAs;
import org.openapis.openapi.operations.SubscribersV1ControllerModifySubscriberChannel;
import org.openapis.openapi.operations.SubscribersV1ControllerUpdateSubscriberChannel;
import org.openapis.openapi.operations.SubscribersV1ControllerUpdateSubscriberOnlineFlag;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class Subscribers {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncSubscribers asyncSDK;
    private final Preferences preferences;
    private final SubscribersTopics topics;
    private final Credentials credentials;
    private final SubscribersMessages2 messages;

    Subscribers(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.preferences = new Preferences(this.sdkConfiguration);
        this.topics = new SubscribersTopics(this.sdkConfiguration);
        this.credentials = new Credentials(this.sdkConfiguration);
        this.messages = new SubscribersMessages2(this.sdkConfiguration);
        this.asyncSDK = new AsyncSubscribers(this, sdkConfiguration);
    }

    public final Preferences preferences() {
        return preferences;
    }

    public final SubscribersTopics topics() {
        return topics;
    }

    public final Credentials credentials() {
        return credentials;
    }

    public final SubscribersMessages2 messages() {
        return messages;
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncSubscribers async() {
        return asyncSDK;
    }

    /**
     * Search subscribers
     * 
     * <p>Search subscribers by their **email**, **phone**, **subscriberId** and **name**.
     * The search is case sensitive and supports pagination.Checkout all available filters in the query
     * section.
     * 
     * @return The call builder
     */
    public SubscribersControllerSearchSubscribersRequestBuilder search() {
        return new SubscribersControllerSearchSubscribersRequestBuilder(sdkConfiguration);
    }

    /**
     * Search subscribers
     * 
     * <p>Search subscribers by their **email**, **phone**, **subscriberId** and **name**.
     * The search is case sensitive and supports pagination.Checkout all available filters in the query
     * section.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerSearchSubscribersResponse search(@Nonnull SubscribersControllerSearchSubscribersRequest request) {
        return search(request, null);
    }

    /**
     * Search subscribers
     * 
     * <p>Search subscribers by their **email**, **phone**, **subscriberId** and **name**.
     * The search is case sensitive and supports pagination.Checkout all available filters in the query
     * section.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerSearchSubscribersResponse search(@Nonnull SubscribersControllerSearchSubscribersRequest request, @Nullable Options options) {
        RequestOperation<SubscribersControllerSearchSubscribersRequest, SubscribersControllerSearchSubscribersResponse> operation
              = new SubscribersControllerSearchSubscribers.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create a subscriber
     * 
     * <p>Create a subscriber with the subscriber attributes.
     * **subscriberId** is a required field, rest other fields are optional, if the subscriber already
     * exists, it will be updated
     * 
     * @return The call builder
     */
    public SubscribersControllerCreateSubscriberRequestBuilder create() {
        return new SubscribersControllerCreateSubscriberRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a subscriber
     * 
     * <p>Create a subscriber with the subscriber attributes.
     * **subscriberId** is a required field, rest other fields are optional, if the subscriber already
     * exists, it will be updated
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerCreateSubscriberResponse create(@Nonnull CreateSubscriberRequestDto body) {
        return create(null, null, body,
            null);
    }

    /**
     * Create a subscriber
     * 
     * <p>Create a subscriber with the subscriber attributes.
     * **subscriberId** is a required field, rest other fields are optional, if the subscriber already
     * exists, it will be updated
     * 
     * @param failIfExists If true, the request will fail if a subscriber with the same subscriberId already exists
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerCreateSubscriberResponse create(
            @Nullable Boolean failIfExists, @Nullable String idempotencyKey,
            @Nonnull CreateSubscriberRequestDto body, @Nullable Options options) {
        SubscribersControllerCreateSubscriberRequest request = new SubscribersControllerCreateSubscriberRequest(failIfExists, idempotencyKey, body);
        RequestOperation<SubscribersControllerCreateSubscriberRequest, SubscribersControllerCreateSubscriberResponse> operation
              = new SubscribersControllerCreateSubscriber.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a subscriber
     * 
     * <p>Retrieve a subscriber by its unique key identifier **subscriberId**.
     * **subscriberId** field is required.
     * 
     * @return The call builder
     */
    public SubscribersControllerGetSubscriberRequestBuilder get() {
        return new SubscribersControllerGetSubscriberRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a subscriber
     * 
     * <p>Retrieve a subscriber by its unique key identifier **subscriberId**.
     * **subscriberId** field is required.
     * 
     * @param subscriberId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerGetSubscriberResponse get(@Nonnull String subscriberId) {
        return get(subscriberId, null, null);
    }

    /**
     * Retrieve a subscriber
     * 
     * <p>Retrieve a subscriber by its unique key identifier **subscriberId**.
     * **subscriberId** field is required.
     * 
     * @param subscriberId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerGetSubscriberResponse get(
            @Nonnull String subscriberId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        SubscribersControllerGetSubscriberRequest request = new SubscribersControllerGetSubscriberRequest(subscriberId, idempotencyKey);
        RequestOperation<SubscribersControllerGetSubscriberRequest, SubscribersControllerGetSubscriberResponse> operation
              = new SubscribersControllerGetSubscriber.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a subscriber
     * 
     * <p>Update a subscriber by its unique key identifier **subscriberId**.
     * **subscriberId** is a required field, rest other fields are optional
     * 
     * @return The call builder
     */
    public SubscribersControllerPatchSubscriberRequestBuilder update() {
        return new SubscribersControllerPatchSubscriberRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a subscriber
     * 
     * <p>Update a subscriber by its unique key identifier **subscriberId**.
     * **subscriberId** is a required field, rest other fields are optional
     * 
     * @param subscriberId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerPatchSubscriberResponse update(@Nonnull String subscriberId, @Nonnull PatchSubscriberRequestDto body) {
        return update(subscriberId, null, body,
            null);
    }

    /**
     * Update a subscriber
     * 
     * <p>Update a subscriber by its unique key identifier **subscriberId**.
     * **subscriberId** is a required field, rest other fields are optional
     * 
     * @param subscriberId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerPatchSubscriberResponse update(
            @Nonnull String subscriberId, @Nullable String idempotencyKey,
            @Nonnull PatchSubscriberRequestDto body, @Nullable Options options) {
        SubscribersControllerPatchSubscriberRequest request = new SubscribersControllerPatchSubscriberRequest(subscriberId, idempotencyKey, body);
        RequestOperation<SubscribersControllerPatchSubscriberRequest, SubscribersControllerPatchSubscriberResponse> operation
              = new SubscribersControllerPatchSubscriber.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete a subscriber
     * 
     * <p>Deletes a subscriber entity from the Novu platform along with associated messages, preferences, and
     * topic subscriptions.
     * **subscriberId** is a required field.
     * 
     * @return The call builder
     */
    public SubscribersControllerRemoveSubscriberRequestBuilder removeSubscriber() {
        return new SubscribersControllerRemoveSubscriberRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a subscriber
     * 
     * <p>Deletes a subscriber entity from the Novu platform along with associated messages, preferences, and
     * topic subscriptions.
     * **subscriberId** is a required field.
     * 
     * @param subscriberId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerRemoveSubscriberResponse removeSubscriber(@Nonnull String subscriberId) {
        return removeSubscriber(subscriberId, null, null);
    }

    /**
     * Delete a subscriber
     * 
     * <p>Deletes a subscriber entity from the Novu platform along with associated messages, preferences, and
     * topic subscriptions.
     * **subscriberId** is a required field.
     * 
     * @param subscriberId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerRemoveSubscriberResponse removeSubscriber(
            @Nonnull String subscriberId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        SubscribersControllerRemoveSubscriberRequest request = new SubscribersControllerRemoveSubscriberRequest(subscriberId, idempotencyKey);
        RequestOperation<SubscribersControllerRemoveSubscriberRequest, SubscribersControllerRemoveSubscriberResponse> operation
              = new SubscribersControllerRemoveSubscriber.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Bulk create subscribers
     * 
     * <p>Using this endpoint multiple subscribers can be created at once. The bulk API is limited to 500
     * subscribers per request.
     * 
     * @return The call builder
     */
    public SubscribersV1ControllerBulkCreateSubscribersRequestBuilder createBulk() {
        return new SubscribersV1ControllerBulkCreateSubscribersRequestBuilder(sdkConfiguration);
    }

    /**
     * Bulk create subscribers
     * 
     * <p>Using this endpoint multiple subscribers can be created at once. The bulk API is limited to 500
     * subscribers per request.
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerBulkCreateSubscribersResponse createBulk(@Nonnull BulkSubscriberCreateDto body) {
        return createBulk(null, body, null);
    }

    /**
     * Bulk create subscribers
     * 
     * <p>Using this endpoint multiple subscribers can be created at once. The bulk API is limited to 500
     * subscribers per request.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerBulkCreateSubscribersResponse createBulk(
            @Nullable String idempotencyKey, @Nonnull BulkSubscriberCreateDto body,
            @Nullable Options options) {
        SubscribersV1ControllerBulkCreateSubscribersRequest request = new SubscribersV1ControllerBulkCreateSubscribersRequest(idempotencyKey, body);
        RequestOperation<SubscribersV1ControllerBulkCreateSubscribersRequest, SubscribersV1ControllerBulkCreateSubscribersResponse> operation
              = new SubscribersV1ControllerBulkCreateSubscribers.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update subscriber preferences
     * 
     * <p>Update subscriber preferences by its unique key identifier **subscriberId**.
     * **workflowId** is optional field, if provided, this API will update that workflow preference,
     * otherwise it will update global preferences
     * 
     * @return The call builder
     */
    public SubscribersControllerUpdateSubscriberPreferencesRequestBuilder updatePreferences() {
        return new SubscribersControllerUpdateSubscriberPreferencesRequestBuilder(sdkConfiguration);
    }

    /**
     * Update subscriber preferences
     * 
     * <p>Update subscriber preferences by its unique key identifier **subscriberId**.
     * **workflowId** is optional field, if provided, this API will update that workflow preference,
     * otherwise it will update global preferences
     * 
     * @param subscriberId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerUpdateSubscriberPreferencesResponse updatePreferences(@Nonnull String subscriberId, @Nonnull PatchSubscriberPreferencesDto body) {
        return updatePreferences(subscriberId, null, body,
            null);
    }

    /**
     * Update subscriber preferences
     * 
     * <p>Update subscriber preferences by its unique key identifier **subscriberId**.
     * **workflowId** is optional field, if provided, this API will update that workflow preference,
     * otherwise it will update global preferences
     * 
     * @param subscriberId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerUpdateSubscriberPreferencesResponse updatePreferences(
            @Nonnull String subscriberId, @Nullable String idempotencyKey,
            @Nonnull PatchSubscriberPreferencesDto body, @Nullable Options options) {
        SubscribersControllerUpdateSubscriberPreferencesRequest request = new SubscribersControllerUpdateSubscriberPreferencesRequest(subscriberId, idempotencyKey, body);
        RequestOperation<SubscribersControllerUpdateSubscriberPreferencesRequest, SubscribersControllerUpdateSubscriberPreferencesResponse> operation
              = new SubscribersControllerUpdateSubscriberPreferences.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update provider credentials
     * 
     * <p>Update credentials for a provider such as **slack** and **FCM**.
     * **providerId** is required field. This API creates the **deviceTokens** or replaces the existing
     * ones.
     * 
     * @return The call builder
     */
    public SubscribersV1ControllerUpdateSubscriberChannelRequestBuilder updateCredentials() {
        return new SubscribersV1ControllerUpdateSubscriberChannelRequestBuilder(sdkConfiguration);
    }

    /**
     * Update provider credentials
     * 
     * <p>Update credentials for a provider such as **slack** and **FCM**.
     * **providerId** is required field. This API creates the **deviceTokens** or replaces the existing
     * ones.
     * 
     * @param subscriberId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerUpdateSubscriberChannelResponse updateCredentials(@Nonnull String subscriberId, @Nonnull UpdateSubscriberChannelRequestDto body) {
        return updateCredentials(subscriberId, null, body,
            null);
    }

    /**
     * Update provider credentials
     * 
     * <p>Update credentials for a provider such as **slack** and **FCM**.
     * **providerId** is required field. This API creates the **deviceTokens** or replaces the existing
     * ones.
     * 
     * @param subscriberId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerUpdateSubscriberChannelResponse updateCredentials(
            @Nonnull String subscriberId, @Nullable String idempotencyKey,
            @Nonnull UpdateSubscriberChannelRequestDto body, @Nullable Options options) {
        SubscribersV1ControllerUpdateSubscriberChannelRequest request = new SubscribersV1ControllerUpdateSubscriberChannelRequest(subscriberId, idempotencyKey, body);
        RequestOperation<SubscribersV1ControllerUpdateSubscriberChannelRequest, SubscribersV1ControllerUpdateSubscriberChannelResponse> operation
              = new SubscribersV1ControllerUpdateSubscriberChannel.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Upsert provider credentials
     * 
     * <p>Upsert credentials for a provider such as **slack** and **FCM**.
     * **providerId** is required field. This API creates **deviceTokens** or appends to the existing ones.
     * 
     * @return The call builder
     */
    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder appendCredentials() {
        return new SubscribersV1ControllerModifySubscriberChannelRequestBuilder(sdkConfiguration);
    }

    /**
     * Upsert provider credentials
     * 
     * <p>Upsert credentials for a provider such as **slack** and **FCM**.
     * **providerId** is required field. This API creates **deviceTokens** or appends to the existing ones.
     * 
     * @param subscriberId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerModifySubscriberChannelResponse appendCredentials(@Nonnull String subscriberId, @Nonnull UpdateSubscriberChannelRequestDto body) {
        return appendCredentials(subscriberId, null, body,
            null);
    }

    /**
     * Upsert provider credentials
     * 
     * <p>Upsert credentials for a provider such as **slack** and **FCM**.
     * **providerId** is required field. This API creates **deviceTokens** or appends to the existing ones.
     * 
     * @param subscriberId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerModifySubscriberChannelResponse appendCredentials(
            @Nonnull String subscriberId, @Nullable String idempotencyKey,
            @Nonnull UpdateSubscriberChannelRequestDto body, @Nullable Options options) {
        SubscribersV1ControllerModifySubscriberChannelRequest request = new SubscribersV1ControllerModifySubscriberChannelRequest(subscriberId, idempotencyKey, body);
        RequestOperation<SubscribersV1ControllerModifySubscriberChannelRequest, SubscribersV1ControllerModifySubscriberChannelResponse> operation
              = new SubscribersV1ControllerModifySubscriberChannel.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update notifications state
     * 
     * <p>Update subscriber's multiple in-app (inbox) notifications state such as seen, read, unseen or unread
     * by **subscriberId**.
     * **messageId** is of type mongodbId of notifications
     * 
     * @return The call builder
     */
    public SubscribersV1ControllerMarkMessagesAsRequestBuilder markAllMessagesAs() {
        return new SubscribersV1ControllerMarkMessagesAsRequestBuilder(sdkConfiguration);
    }

    /**
     * Update notifications state
     * 
     * <p>Update subscriber's multiple in-app (inbox) notifications state such as seen, read, unseen or unread
     * by **subscriberId**.
     * **messageId** is of type mongodbId of notifications
     * 
     * @param subscriberId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerMarkMessagesAsResponse markAllMessagesAs(@Nonnull String subscriberId, @Nonnull MessageMarkAsRequestDto body) {
        return markAllMessagesAs(subscriberId, null, body,
            null);
    }

    /**
     * Update notifications state
     * 
     * <p>Update subscriber's multiple in-app (inbox) notifications state such as seen, read, unseen or unread
     * by **subscriberId**.
     * **messageId** is of type mongodbId of notifications
     * 
     * @param subscriberId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerMarkMessagesAsResponse markAllMessagesAs(
            @Nonnull String subscriberId, @Nullable String idempotencyKey,
            @Nonnull MessageMarkAsRequestDto body, @Nullable Options options) {
        SubscribersV1ControllerMarkMessagesAsRequest request = new SubscribersV1ControllerMarkMessagesAsRequest(subscriberId, idempotencyKey, body);
        RequestOperation<SubscribersV1ControllerMarkMessagesAsRequest, SubscribersV1ControllerMarkMessagesAsResponse> operation
              = new SubscribersV1ControllerMarkMessagesAs.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve unseen notifications count
     * 
     * <p>Retrieve unseen in-app (inbox) notifications count for a subscriber by its unique key identifier
     * **subscriberId**.
     * 
     * @return The call builder
     */
    public SubscribersV1ControllerGetUnseenCountRequestBuilder getUnseenCount() {
        return new SubscribersV1ControllerGetUnseenCountRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve unseen notifications count
     * 
     * <p>Retrieve unseen in-app (inbox) notifications count for a subscriber by its unique key identifier
     * **subscriberId**.
     * 
     * @param subscriberId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerGetUnseenCountResponse getUnseenCount(@Nonnull String subscriberId) {
        return getUnseenCount(subscriberId, null, null,
            null, null);
    }

    /**
     * Retrieve unseen notifications count
     * 
     * <p>Retrieve unseen in-app (inbox) notifications count for a subscriber by its unique key identifier
     * **subscriberId**.
     * 
     * @param subscriberId 
     * @param seen Indicates whether to count seen notifications.
     * @param limit The maximum number of notifications to return.
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerGetUnseenCountResponse getUnseenCount(
            @Nonnull String subscriberId, @Nullable Boolean seen,
            @Nullable Double limit, @Nullable String idempotencyKey,
            @Nullable Options options) {
        SubscribersV1ControllerGetUnseenCountRequest request = new SubscribersV1ControllerGetUnseenCountRequest(
                subscriberId, seen, limit,
                idempotencyKey);
        RequestOperation<SubscribersV1ControllerGetUnseenCountRequest, SubscribersV1ControllerGetUnseenCountResponse> operation
              = new SubscribersV1ControllerGetUnseenCount.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update subscriber online status
     * 
     * <p>Update the subscriber online status by its unique key identifier **subscriberId**
     * 
     * @return The call builder
     */
    public SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder updateOnlineStatus() {
        return new SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder(sdkConfiguration);
    }

    /**
     * Update subscriber online status
     * 
     * <p>Update the subscriber online status by its unique key identifier **subscriberId**
     * 
     * @param subscriberId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse updateOnlineStatus(@Nonnull String subscriberId, @Nonnull UpdateSubscriberOnlineFlagRequestDto body) {
        return updateOnlineStatus(subscriberId, null, body,
            null);
    }

    /**
     * Update subscriber online status
     * 
     * <p>Update the subscriber online status by its unique key identifier **subscriberId**
     * 
     * @param subscriberId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse updateOnlineStatus(
            @Nonnull String subscriberId, @Nullable String idempotencyKey,
            @Nonnull UpdateSubscriberOnlineFlagRequestDto body, @Nullable Options options) {
        SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest request = new SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest(subscriberId, idempotencyKey, body);
        RequestOperation<SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest, SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse> operation
              = new SubscribersV1ControllerUpdateSubscriberOnlineFlag.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
