/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.models.components.BulkUpdateSubscriberPreferencesDto;
import org.openapis.openapi.models.operations.SubscribersControllerBulkUpdateSubscriberPreferencesRequest;
import org.openapis.openapi.models.operations.SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder;
import org.openapis.openapi.models.operations.SubscribersControllerBulkUpdateSubscriberPreferencesResponse;
import org.openapis.openapi.operations.SubscribersControllerBulkUpdateSubscriberPreferences;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class SubscribersPreferences {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncSubscribersPreferences asyncSDK;

    SubscribersPreferences(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncSubscribersPreferences(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncSubscribersPreferences async() {
        return asyncSDK;
    }

    /**
     * Bulk update subscriber preferences
     * 
     * <p>Bulk update subscriber preferences by its unique key identifier **subscriberId**.
     * This API allows updating multiple workflow preferences in a single request.
     * 
     * @return The call builder
     */
    public SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder bulkUpdate() {
        return new SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder(sdkConfiguration);
    }

    /**
     * Bulk update subscriber preferences
     * 
     * <p>Bulk update subscriber preferences by its unique key identifier **subscriberId**.
     * This API allows updating multiple workflow preferences in a single request.
     * 
     * @param subscriberId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerBulkUpdateSubscriberPreferencesResponse bulkUpdate(@Nonnull String subscriberId, @Nonnull BulkUpdateSubscriberPreferencesDto body) {
        return bulkUpdate(subscriberId, null, body,
            null);
    }

    /**
     * Bulk update subscriber preferences
     * 
     * <p>Bulk update subscriber preferences by its unique key identifier **subscriberId**.
     * This API allows updating multiple workflow preferences in a single request.
     * 
     * @param subscriberId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersControllerBulkUpdateSubscriberPreferencesResponse bulkUpdate(
            @Nonnull String subscriberId, @Nullable String idempotencyKey,
            @Nonnull BulkUpdateSubscriberPreferencesDto body, @Nullable Options options) {
        SubscribersControllerBulkUpdateSubscriberPreferencesRequest request = new SubscribersControllerBulkUpdateSubscriberPreferencesRequest(subscriberId, idempotencyKey, body);
        RequestOperation<SubscribersControllerBulkUpdateSubscriberPreferencesRequest, SubscribersControllerBulkUpdateSubscriberPreferencesResponse> operation
              = new SubscribersControllerBulkUpdateSubscriberPreferences.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
