/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.models.operations.TopicsV1ControllerGetTopicSubscriberRequest;
import org.openapis.openapi.models.operations.TopicsV1ControllerGetTopicSubscriberRequestBuilder;
import org.openapis.openapi.models.operations.TopicsV1ControllerGetTopicSubscriberResponse;
import org.openapis.openapi.operations.TopicsV1ControllerGetTopicSubscriber;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class TopicsSubscribers {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncTopicsSubscribers asyncSDK;

    TopicsSubscribers(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncTopicsSubscribers(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncTopicsSubscribers async() {
        return asyncSDK;
    }

    /**
     * Check topic subscriber
     * 
     * <p>Check if a subscriber belongs to a certain topic
     * 
     * @return The call builder
     */
    public TopicsV1ControllerGetTopicSubscriberRequestBuilder get() {
        return new TopicsV1ControllerGetTopicSubscriberRequestBuilder(sdkConfiguration);
    }

    /**
     * Check topic subscriber
     * 
     * <p>Check if a subscriber belongs to a certain topic
     * 
     * @param externalSubscriberId The external subscriber id
     * @param topicKey The topic key
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsV1ControllerGetTopicSubscriberResponse get(@Nonnull String externalSubscriberId, @Nonnull String topicKey) {
        return get(externalSubscriberId, topicKey, null,
            null);
    }

    /**
     * Check topic subscriber
     * 
     * <p>Check if a subscriber belongs to a certain topic
     * 
     * @param externalSubscriberId The external subscriber id
     * @param topicKey The topic key
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsV1ControllerGetTopicSubscriberResponse get(
            @Nonnull String externalSubscriberId, @Nonnull String topicKey,
            @Nullable String idempotencyKey, @Nullable Options options) {
        TopicsV1ControllerGetTopicSubscriberRequest request = new TopicsV1ControllerGetTopicSubscriberRequest(externalSubscriberId, topicKey, idempotencyKey);
        RequestOperation<TopicsV1ControllerGetTopicSubscriberRequest, TopicsV1ControllerGetTopicSubscriberResponse> operation
              = new TopicsV1ControllerGetTopicSubscriber.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
