/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.String;
import org.openapis.openapi.models.components.CreateTopicSubscriptionsRequestDto;
import org.openapis.openapi.models.components.CreateUpdateTopicRequestDto;
import org.openapis.openapi.models.components.UpdateTopicRequestDto;
import org.openapis.openapi.models.operations.TopicsControllerCreateTopicSubscriptionsRequest;
import org.openapis.openapi.models.operations.TopicsControllerCreateTopicSubscriptionsRequestBuilder;
import org.openapis.openapi.models.operations.TopicsControllerCreateTopicSubscriptionsResponse;
import org.openapis.openapi.models.operations.TopicsControllerDeleteTopicRequest;
import org.openapis.openapi.models.operations.TopicsControllerDeleteTopicRequestBuilder;
import org.openapis.openapi.models.operations.TopicsControllerDeleteTopicResponse;
import org.openapis.openapi.models.operations.TopicsControllerGetTopicRequest;
import org.openapis.openapi.models.operations.TopicsControllerGetTopicRequestBuilder;
import org.openapis.openapi.models.operations.TopicsControllerGetTopicResponse;
import org.openapis.openapi.models.operations.TopicsControllerListTopicsRequest;
import org.openapis.openapi.models.operations.TopicsControllerListTopicsRequestBuilder;
import org.openapis.openapi.models.operations.TopicsControllerListTopicsResponse;
import org.openapis.openapi.models.operations.TopicsControllerUpdateTopicRequest;
import org.openapis.openapi.models.operations.TopicsControllerUpdateTopicRequestBuilder;
import org.openapis.openapi.models.operations.TopicsControllerUpdateTopicResponse;
import org.openapis.openapi.models.operations.TopicsControllerUpsertTopicRequest;
import org.openapis.openapi.models.operations.TopicsControllerUpsertTopicRequestBuilder;
import org.openapis.openapi.models.operations.TopicsControllerUpsertTopicResponse;
import org.openapis.openapi.operations.TopicsControllerCreateTopicSubscriptions;
import org.openapis.openapi.operations.TopicsControllerDeleteTopic;
import org.openapis.openapi.operations.TopicsControllerGetTopic;
import org.openapis.openapi.operations.TopicsControllerListTopics;
import org.openapis.openapi.operations.TopicsControllerUpdateTopic;
import org.openapis.openapi.operations.TopicsControllerUpsertTopic;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class Topics {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncTopics asyncSDK;
    private final Subscriptions subscriptions;
    private final TopicsSubscribers subscribers;

    Topics(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.subscriptions = new Subscriptions(this.sdkConfiguration);
        this.subscribers = new TopicsSubscribers(this.sdkConfiguration);
        this.asyncSDK = new AsyncTopics(this, sdkConfiguration);
    }

    public final Subscriptions subscriptions() {
        return subscriptions;
    }

    public final TopicsSubscribers subscribers() {
        return subscribers;
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncTopics async() {
        return asyncSDK;
    }

    /**
     * List all topics
     * 
     * <p>This api returns a paginated list of topics.
     * Topics can be filtered by **key**, **name**, or **includeCursor** to paginate through the list.
     * Checkout all available filters in the query section.
     * 
     * @return The call builder
     */
    public TopicsControllerListTopicsRequestBuilder getAll() {
        return new TopicsControllerListTopicsRequestBuilder(sdkConfiguration);
    }

    /**
     * List all topics
     * 
     * <p>This api returns a paginated list of topics.
     * Topics can be filtered by **key**, **name**, or **includeCursor** to paginate through the list.
     * Checkout all available filters in the query section.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerListTopicsResponse getAll(@Nonnull TopicsControllerListTopicsRequest request) {
        return getAll(request, null);
    }

    /**
     * List all topics
     * 
     * <p>This api returns a paginated list of topics.
     * Topics can be filtered by **key**, **name**, or **includeCursor** to paginate through the list.
     * Checkout all available filters in the query section.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerListTopicsResponse getAll(@Nonnull TopicsControllerListTopicsRequest request, @Nullable Options options) {
        RequestOperation<TopicsControllerListTopicsRequest, TopicsControllerListTopicsResponse> operation
              = new TopicsControllerListTopics.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create a topic
     * 
     * <p>Creates a new topic if it does not exist, or updates an existing topic if it already exists. Use
     * ?failIfExists=true to prevent updates.
     * 
     * @return The call builder
     */
    public TopicsControllerUpsertTopicRequestBuilder create() {
        return new TopicsControllerUpsertTopicRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a topic
     * 
     * <p>Creates a new topic if it does not exist, or updates an existing topic if it already exists. Use
     * ?failIfExists=true to prevent updates.
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerUpsertTopicResponse create(@Nonnull CreateUpdateTopicRequestDto body) {
        return create(null, null, body,
            null);
    }

    /**
     * Create a topic
     * 
     * <p>Creates a new topic if it does not exist, or updates an existing topic if it already exists. Use
     * ?failIfExists=true to prevent updates.
     * 
     * @param failIfExists If true, the request will fail if a topic with the same key already exists
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerUpsertTopicResponse create(
            @Nullable Boolean failIfExists, @Nullable String idempotencyKey,
            @Nonnull CreateUpdateTopicRequestDto body, @Nullable Options options) {
        TopicsControllerUpsertTopicRequest request = new TopicsControllerUpsertTopicRequest(failIfExists, idempotencyKey, body);
        RequestOperation<TopicsControllerUpsertTopicRequest, TopicsControllerUpsertTopicResponse> operation
              = new TopicsControllerUpsertTopic.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a topic
     * 
     * <p>Retrieve a topic by its unique key identifier **topicKey**
     * 
     * @return The call builder
     */
    public TopicsControllerGetTopicRequestBuilder getTopic() {
        return new TopicsControllerGetTopicRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a topic
     * 
     * <p>Retrieve a topic by its unique key identifier **topicKey**
     * 
     * @param topicKey The key identifier of the topic
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerGetTopicResponse getTopic(@Nonnull String topicKey) {
        return getTopic(topicKey, null, null);
    }

    /**
     * Retrieve a topic
     * 
     * <p>Retrieve a topic by its unique key identifier **topicKey**
     * 
     * @param topicKey The key identifier of the topic
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerGetTopicResponse getTopic(
            @Nonnull String topicKey, @Nullable String idempotencyKey,
            @Nullable Options options) {
        TopicsControllerGetTopicRequest request = new TopicsControllerGetTopicRequest(topicKey, idempotencyKey);
        RequestOperation<TopicsControllerGetTopicRequest, TopicsControllerGetTopicResponse> operation
              = new TopicsControllerGetTopic.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a topic
     * 
     * <p>Update a topic name by its unique key identifier **topicKey**
     * 
     * @return The call builder
     */
    public TopicsControllerUpdateTopicRequestBuilder patch() {
        return new TopicsControllerUpdateTopicRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a topic
     * 
     * <p>Update a topic name by its unique key identifier **topicKey**
     * 
     * @param topicKey The key identifier of the topic
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerUpdateTopicResponse patch(@Nonnull String topicKey, @Nonnull UpdateTopicRequestDto body) {
        return patch(topicKey, null, body,
            null);
    }

    /**
     * Update a topic
     * 
     * <p>Update a topic name by its unique key identifier **topicKey**
     * 
     * @param topicKey The key identifier of the topic
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerUpdateTopicResponse patch(
            @Nonnull String topicKey, @Nullable String idempotencyKey,
            @Nonnull UpdateTopicRequestDto body, @Nullable Options options) {
        TopicsControllerUpdateTopicRequest request = new TopicsControllerUpdateTopicRequest(topicKey, idempotencyKey, body);
        RequestOperation<TopicsControllerUpdateTopicRequest, TopicsControllerUpdateTopicResponse> operation
              = new TopicsControllerUpdateTopic.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete a topic
     * 
     * <p>Delete a topic by its unique key identifier **topicKey**.
     * This action is irreversible and will remove all subscriptions to the topic.
     * 
     * @return The call builder
     */
    public TopicsControllerDeleteTopicRequestBuilder remove() {
        return new TopicsControllerDeleteTopicRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a topic
     * 
     * <p>Delete a topic by its unique key identifier **topicKey**.
     * This action is irreversible and will remove all subscriptions to the topic.
     * 
     * @param topicKey The key identifier of the topic
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerDeleteTopicResponse remove(@Nonnull String topicKey) {
        return remove(topicKey, null, null);
    }

    /**
     * Delete a topic
     * 
     * <p>Delete a topic by its unique key identifier **topicKey**.
     * This action is irreversible and will remove all subscriptions to the topic.
     * 
     * @param topicKey The key identifier of the topic
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerDeleteTopicResponse remove(
            @Nonnull String topicKey, @Nullable String idempotencyKey,
            @Nullable Options options) {
        TopicsControllerDeleteTopicRequest request = new TopicsControllerDeleteTopicRequest(topicKey, idempotencyKey);
        RequestOperation<TopicsControllerDeleteTopicRequest, TopicsControllerDeleteTopicResponse> operation
              = new TopicsControllerDeleteTopic.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create topic subscriptions
     * 
     * <p>This api will create subscription for subscriberIds for a topic.
     * Its like subscribing to a common interest group. if topic does not exist, it will be created.
     * 
     * @return The call builder
     */
    public TopicsControllerCreateTopicSubscriptionsRequestBuilder createSubscription() {
        return new TopicsControllerCreateTopicSubscriptionsRequestBuilder(sdkConfiguration);
    }

    /**
     * Create topic subscriptions
     * 
     * <p>This api will create subscription for subscriberIds for a topic.
     * Its like subscribing to a common interest group. if topic does not exist, it will be created.
     * 
     * @param topicKey The key identifier of the topic
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerCreateTopicSubscriptionsResponse createSubscription(@Nonnull String topicKey, @Nonnull CreateTopicSubscriptionsRequestDto body) {
        return createSubscription(topicKey, null, body,
            null);
    }

    /**
     * Create topic subscriptions
     * 
     * <p>This api will create subscription for subscriberIds for a topic.
     * Its like subscribing to a common interest group. if topic does not exist, it will be created.
     * 
     * @param topicKey The key identifier of the topic
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TopicsControllerCreateTopicSubscriptionsResponse createSubscription(
            @Nonnull String topicKey, @Nullable String idempotencyKey,
            @Nonnull CreateTopicSubscriptionsRequestDto body, @Nullable Options options) {
        TopicsControllerCreateTopicSubscriptionsRequest request = new TopicsControllerCreateTopicSubscriptionsRequest(topicKey, idempotencyKey, body);
        RequestOperation<TopicsControllerCreateTopicSubscriptionsRequest, TopicsControllerCreateTopicSubscriptionsResponse> operation
              = new TopicsControllerCreateTopicSubscriptions.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
