/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.models.components.CreateTranslationRequestDto;
import org.openapis.openapi.models.components.ImportMasterJsonRequestDto;
import org.openapis.openapi.models.operations.TranslationControllerCreateTranslationEndpointRequest;
import org.openapis.openapi.models.operations.TranslationControllerCreateTranslationEndpointRequestBuilder;
import org.openapis.openapi.models.operations.TranslationControllerCreateTranslationEndpointResponse;
import org.openapis.openapi.models.operations.TranslationControllerDeleteTranslationEndpointRequest;
import org.openapis.openapi.models.operations.TranslationControllerDeleteTranslationEndpointRequestBuilder;
import org.openapis.openapi.models.operations.TranslationControllerDeleteTranslationEndpointResourceType;
import org.openapis.openapi.models.operations.TranslationControllerDeleteTranslationEndpointResponse;
import org.openapis.openapi.models.operations.TranslationControllerGetSingleTranslationRequest;
import org.openapis.openapi.models.operations.TranslationControllerGetSingleTranslationRequestBuilder;
import org.openapis.openapi.models.operations.TranslationControllerGetSingleTranslationResourceType;
import org.openapis.openapi.models.operations.TranslationControllerGetSingleTranslationResponse;
import org.openapis.openapi.models.operations.TranslationControllerImportMasterJsonEndpointRequest;
import org.openapis.openapi.models.operations.TranslationControllerImportMasterJsonEndpointRequestBuilder;
import org.openapis.openapi.models.operations.TranslationControllerImportMasterJsonEndpointResponse;
import org.openapis.openapi.models.operations.TranslationControllerUploadMasterJsonEndpointRequest;
import org.openapis.openapi.models.operations.TranslationControllerUploadMasterJsonEndpointRequestBody;
import org.openapis.openapi.models.operations.TranslationControllerUploadMasterJsonEndpointRequestBuilder;
import org.openapis.openapi.models.operations.TranslationControllerUploadMasterJsonEndpointResponse;
import org.openapis.openapi.models.operations.TranslationControllerUploadTranslationFilesRequest;
import org.openapis.openapi.models.operations.TranslationControllerUploadTranslationFilesRequestBody;
import org.openapis.openapi.models.operations.TranslationControllerUploadTranslationFilesRequestBuilder;
import org.openapis.openapi.models.operations.TranslationControllerUploadTranslationFilesResponse;
import org.openapis.openapi.operations.TranslationControllerCreateTranslationEndpoint;
import org.openapis.openapi.operations.TranslationControllerDeleteTranslationEndpoint;
import org.openapis.openapi.operations.TranslationControllerGetSingleTranslation;
import org.openapis.openapi.operations.TranslationControllerImportMasterJsonEndpoint;
import org.openapis.openapi.operations.TranslationControllerUploadMasterJsonEndpoint;
import org.openapis.openapi.operations.TranslationControllerUploadTranslationFiles;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class Translations {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncTranslations asyncSDK;
    private final Groups groups;

    Translations(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.groups = new Groups(this.sdkConfiguration);
        this.asyncSDK = new AsyncTranslations(this, sdkConfiguration);
    }

    public final Groups groups() {
        return groups;
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncTranslations async() {
        return asyncSDK;
    }

    /**
     * Create a translation
     * 
     * <p>Create a translation for a specific workflow and locale, if the translation already exists, it will
     * be updated
     * 
     * @return The call builder
     */
    public TranslationControllerCreateTranslationEndpointRequestBuilder create() {
        return new TranslationControllerCreateTranslationEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a translation
     * 
     * <p>Create a translation for a specific workflow and locale, if the translation already exists, it will
     * be updated
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerCreateTranslationEndpointResponse create(@Nonnull CreateTranslationRequestDto body) {
        return create(null, body, null);
    }

    /**
     * Create a translation
     * 
     * <p>Create a translation for a specific workflow and locale, if the translation already exists, it will
     * be updated
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerCreateTranslationEndpointResponse create(
            @Nullable String idempotencyKey, @Nonnull CreateTranslationRequestDto body,
            @Nullable Options options) {
        TranslationControllerCreateTranslationEndpointRequest request = new TranslationControllerCreateTranslationEndpointRequest(idempotencyKey, body);
        RequestOperation<TranslationControllerCreateTranslationEndpointRequest, TranslationControllerCreateTranslationEndpointResponse> operation
              = new TranslationControllerCreateTranslationEndpoint.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a translation
     * 
     * <p>Retrieve a specific translation by resource type, resource ID and locale
     * 
     * @return The call builder
     */
    public TranslationControllerGetSingleTranslationRequestBuilder get() {
        return new TranslationControllerGetSingleTranslationRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a translation
     * 
     * <p>Retrieve a specific translation by resource type, resource ID and locale
     * 
     * @param resourceType Resource type
     * @param resourceId Resource ID
     * @param locale Locale code
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerGetSingleTranslationResponse get(
            @Nonnull TranslationControllerGetSingleTranslationResourceType resourceType, @Nonnull String resourceId,
            @Nonnull String locale) {
        return get(resourceType, resourceId, locale,
            null, null);
    }

    /**
     * Retrieve a translation
     * 
     * <p>Retrieve a specific translation by resource type, resource ID and locale
     * 
     * @param resourceType Resource type
     * @param resourceId Resource ID
     * @param locale Locale code
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerGetSingleTranslationResponse get(
            @Nonnull TranslationControllerGetSingleTranslationResourceType resourceType, @Nonnull String resourceId,
            @Nonnull String locale, @Nullable String idempotencyKey,
            @Nullable Options options) {
        TranslationControllerGetSingleTranslationRequest request = new TranslationControllerGetSingleTranslationRequest(
                resourceType, resourceId, locale,
                idempotencyKey);
        RequestOperation<TranslationControllerGetSingleTranslationRequest, TranslationControllerGetSingleTranslationResponse> operation
              = new TranslationControllerGetSingleTranslation.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete a translation
     * 
     * <p>Delete a specific translation by resource type, resource ID and locale
     * 
     * @return The call builder
     */
    public TranslationControllerDeleteTranslationEndpointRequestBuilder delete() {
        return new TranslationControllerDeleteTranslationEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a translation
     * 
     * <p>Delete a specific translation by resource type, resource ID and locale
     * 
     * @param resourceType Resource type
     * @param resourceId Resource ID
     * @param locale Locale code
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerDeleteTranslationEndpointResponse delete(
            @Nonnull TranslationControllerDeleteTranslationEndpointResourceType resourceType, @Nonnull String resourceId,
            @Nonnull String locale) {
        return delete(resourceType, resourceId, locale,
            null, null);
    }

    /**
     * Delete a translation
     * 
     * <p>Delete a specific translation by resource type, resource ID and locale
     * 
     * @param resourceType Resource type
     * @param resourceId Resource ID
     * @param locale Locale code
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerDeleteTranslationEndpointResponse delete(
            @Nonnull TranslationControllerDeleteTranslationEndpointResourceType resourceType, @Nonnull String resourceId,
            @Nonnull String locale, @Nullable String idempotencyKey,
            @Nullable Options options) {
        TranslationControllerDeleteTranslationEndpointRequest request = new TranslationControllerDeleteTranslationEndpointRequest(
                resourceType, resourceId, locale,
                idempotencyKey);
        RequestOperation<TranslationControllerDeleteTranslationEndpointRequest, TranslationControllerDeleteTranslationEndpointResponse> operation
              = new TranslationControllerDeleteTranslationEndpoint.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Upload translation files
     * 
     * <p>Upload one or more JSON translation files for a specific workflow. Files name must match the locale,
     * e.g. en_US.json.
     * 
     * <p>Supports both "files" and "files[]" field names for backwards compatibility.
     * 
     * @return The call builder
     */
    public TranslationControllerUploadTranslationFilesRequestBuilder upload() {
        return new TranslationControllerUploadTranslationFilesRequestBuilder(sdkConfiguration);
    }

    /**
     * Upload translation files
     * 
     * <p>Upload one or more JSON translation files for a specific workflow. Files name must match the locale,
     * e.g. en_US.json.
     * 
     * <p>Supports both "files" and "files[]" field names for backwards compatibility.
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerUploadTranslationFilesResponse upload(@Nonnull TranslationControllerUploadTranslationFilesRequestBody body) {
        return upload(null, body, null);
    }

    /**
     * Upload translation files
     * 
     * <p>Upload one or more JSON translation files for a specific workflow. Files name must match the locale,
     * e.g. en_US.json.
     * 
     * <p>Supports both "files" and "files[]" field names for backwards compatibility.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerUploadTranslationFilesResponse upload(
            @Nullable String idempotencyKey, @Nonnull TranslationControllerUploadTranslationFilesRequestBody body,
            @Nullable Options options) {
        TranslationControllerUploadTranslationFilesRequest request = new TranslationControllerUploadTranslationFilesRequest(idempotencyKey, body);
        RequestOperation<TranslationControllerUploadTranslationFilesRequest, TranslationControllerUploadTranslationFilesResponse> operation
              = new TranslationControllerUploadTranslationFiles.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Import master translations JSON
     * 
     * <p>Import translations for multiple workflows from master JSON format for a specific locale
     * 
     * @return The call builder
     */
    public TranslationControllerImportMasterJsonEndpointRequestBuilder importMasterJson() {
        return new TranslationControllerImportMasterJsonEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Import master translations JSON
     * 
     * <p>Import translations for multiple workflows from master JSON format for a specific locale
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerImportMasterJsonEndpointResponse importMasterJson(@Nonnull ImportMasterJsonRequestDto body) {
        return importMasterJson(null, body, null);
    }

    /**
     * Import master translations JSON
     * 
     * <p>Import translations for multiple workflows from master JSON format for a specific locale
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerImportMasterJsonEndpointResponse importMasterJson(
            @Nullable String idempotencyKey, @Nonnull ImportMasterJsonRequestDto body,
            @Nullable Options options) {
        TranslationControllerImportMasterJsonEndpointRequest request = new TranslationControllerImportMasterJsonEndpointRequest(idempotencyKey, body);
        RequestOperation<TranslationControllerImportMasterJsonEndpointRequest, TranslationControllerImportMasterJsonEndpointResponse> operation
              = new TranslationControllerImportMasterJsonEndpoint.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Upload master translations JSON file
     * 
     * <p>Upload a master JSON file containing translations for multiple workflows. Locale is automatically
     * detected from filename (e.g., en_US.json)
     * 
     * @return The call builder
     */
    public TranslationControllerUploadMasterJsonEndpointRequestBuilder uploadMasterJson() {
        return new TranslationControllerUploadMasterJsonEndpointRequestBuilder(sdkConfiguration);
    }

    /**
     * Upload master translations JSON file
     * 
     * <p>Upload a master JSON file containing translations for multiple workflows. Locale is automatically
     * detected from filename (e.g., en_US.json)
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerUploadMasterJsonEndpointResponse uploadMasterJson(@Nonnull TranslationControllerUploadMasterJsonEndpointRequestBody body) {
        return uploadMasterJson(null, body, null);
    }

    /**
     * Upload master translations JSON file
     * 
     * <p>Upload a master JSON file containing translations for multiple workflows. Locale is automatically
     * detected from filename (e.g., en_US.json)
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public TranslationControllerUploadMasterJsonEndpointResponse uploadMasterJson(
            @Nullable String idempotencyKey, @Nonnull TranslationControllerUploadMasterJsonEndpointRequestBody body,
            @Nullable Options options) {
        TranslationControllerUploadMasterJsonEndpointRequest request = new TranslationControllerUploadMasterJsonEndpointRequest(idempotencyKey, body);
        RequestOperation<TranslationControllerUploadMasterJsonEndpointRequest, TranslationControllerUploadMasterJsonEndpointResponse> operation
              = new TranslationControllerUploadMasterJsonEndpoint.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
