/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.models.components.CreateWorkflowDto;
import org.openapis.openapi.models.components.PatchWorkflowDto;
import org.openapis.openapi.models.components.SyncWorkflowDto;
import org.openapis.openapi.models.components.UpdateWorkflowDto;
import org.openapis.openapi.models.operations.WorkflowControllerCreateRequest;
import org.openapis.openapi.models.operations.WorkflowControllerCreateRequestBuilder;
import org.openapis.openapi.models.operations.WorkflowControllerCreateResponse;
import org.openapis.openapi.models.operations.WorkflowControllerGetWorkflowRequest;
import org.openapis.openapi.models.operations.WorkflowControllerGetWorkflowRequestBuilder;
import org.openapis.openapi.models.operations.WorkflowControllerGetWorkflowResponse;
import org.openapis.openapi.models.operations.WorkflowControllerGetWorkflowStepDataRequest;
import org.openapis.openapi.models.operations.WorkflowControllerGetWorkflowStepDataRequestBuilder;
import org.openapis.openapi.models.operations.WorkflowControllerGetWorkflowStepDataResponse;
import org.openapis.openapi.models.operations.WorkflowControllerPatchWorkflowRequest;
import org.openapis.openapi.models.operations.WorkflowControllerPatchWorkflowRequestBuilder;
import org.openapis.openapi.models.operations.WorkflowControllerPatchWorkflowResponse;
import org.openapis.openapi.models.operations.WorkflowControllerRemoveWorkflowRequest;
import org.openapis.openapi.models.operations.WorkflowControllerRemoveWorkflowRequestBuilder;
import org.openapis.openapi.models.operations.WorkflowControllerRemoveWorkflowResponse;
import org.openapis.openapi.models.operations.WorkflowControllerSearchWorkflowsRequest;
import org.openapis.openapi.models.operations.WorkflowControllerSearchWorkflowsRequestBuilder;
import org.openapis.openapi.models.operations.WorkflowControllerSearchWorkflowsResponse;
import org.openapis.openapi.models.operations.WorkflowControllerSyncRequest;
import org.openapis.openapi.models.operations.WorkflowControllerSyncRequestBuilder;
import org.openapis.openapi.models.operations.WorkflowControllerSyncResponse;
import org.openapis.openapi.models.operations.WorkflowControllerUpdateRequest;
import org.openapis.openapi.models.operations.WorkflowControllerUpdateRequestBuilder;
import org.openapis.openapi.models.operations.WorkflowControllerUpdateResponse;
import org.openapis.openapi.operations.WorkflowControllerCreate;
import org.openapis.openapi.operations.WorkflowControllerGetWorkflow;
import org.openapis.openapi.operations.WorkflowControllerGetWorkflowStepData;
import org.openapis.openapi.operations.WorkflowControllerPatchWorkflow;
import org.openapis.openapi.operations.WorkflowControllerRemoveWorkflow;
import org.openapis.openapi.operations.WorkflowControllerSearchWorkflows;
import org.openapis.openapi.operations.WorkflowControllerSync;
import org.openapis.openapi.operations.WorkflowControllerUpdate;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class Workflows {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncWorkflows asyncSDK;

    Workflows(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncWorkflows(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncWorkflows async() {
        return asyncSDK;
    }

    /**
     * Create a workflow
     * 
     * <p>Creates a new workflow in the Novu Cloud environment
     * 
     * @return The call builder
     */
    public WorkflowControllerCreateRequestBuilder create() {
        return new WorkflowControllerCreateRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a workflow
     * 
     * <p>Creates a new workflow in the Novu Cloud environment
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerCreateResponse create(@Nonnull CreateWorkflowDto body) {
        return create(null, body, null);
    }

    /**
     * Create a workflow
     * 
     * <p>Creates a new workflow in the Novu Cloud environment
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerCreateResponse create(
            @Nullable String idempotencyKey, @Nonnull CreateWorkflowDto body,
            @Nullable Options options) {
        WorkflowControllerCreateRequest request = new WorkflowControllerCreateRequest(idempotencyKey, body);
        RequestOperation<WorkflowControllerCreateRequest, WorkflowControllerCreateResponse> operation
              = new WorkflowControllerCreate.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List all workflows
     * 
     * <p>Retrieves a list of workflows with optional filtering and pagination
     * 
     * @return The call builder
     */
    public WorkflowControllerSearchWorkflowsRequestBuilder list() {
        return new WorkflowControllerSearchWorkflowsRequestBuilder(sdkConfiguration);
    }

    /**
     * List all workflows
     * 
     * <p>Retrieves a list of workflows with optional filtering and pagination
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerSearchWorkflowsResponse list(@Nonnull WorkflowControllerSearchWorkflowsRequest request) {
        return list(request, null);
    }

    /**
     * List all workflows
     * 
     * <p>Retrieves a list of workflows with optional filtering and pagination
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerSearchWorkflowsResponse list(@Nonnull WorkflowControllerSearchWorkflowsRequest request, @Nullable Options options) {
        RequestOperation<WorkflowControllerSearchWorkflowsRequest, WorkflowControllerSearchWorkflowsResponse> operation
              = new WorkflowControllerSearchWorkflows.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a workflow
     * 
     * <p>Updates the details of an existing workflow, here **workflowId** is the identifier of the workflow
     * 
     * @return The call builder
     */
    public WorkflowControllerUpdateRequestBuilder update() {
        return new WorkflowControllerUpdateRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a workflow
     * 
     * <p>Updates the details of an existing workflow, here **workflowId** is the identifier of the workflow
     * 
     * @param workflowId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerUpdateResponse update(@Nonnull String workflowId, @Nonnull UpdateWorkflowDto body) {
        return update(workflowId, null, body,
            null);
    }

    /**
     * Update a workflow
     * 
     * <p>Updates the details of an existing workflow, here **workflowId** is the identifier of the workflow
     * 
     * @param workflowId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerUpdateResponse update(
            @Nonnull String workflowId, @Nullable String idempotencyKey,
            @Nonnull UpdateWorkflowDto body, @Nullable Options options) {
        WorkflowControllerUpdateRequest request = new WorkflowControllerUpdateRequest(workflowId, idempotencyKey, body);
        RequestOperation<WorkflowControllerUpdateRequest, WorkflowControllerUpdateResponse> operation
              = new WorkflowControllerUpdate.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a workflow
     * 
     * <p>Fetches details of a specific workflow by its unique identifier **workflowId**
     * 
     * @return The call builder
     */
    public WorkflowControllerGetWorkflowRequestBuilder get() {
        return new WorkflowControllerGetWorkflowRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a workflow
     * 
     * <p>Fetches details of a specific workflow by its unique identifier **workflowId**
     * 
     * @param workflowId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerGetWorkflowResponse get(@Nonnull String workflowId) {
        return get(workflowId, null, null,
            null);
    }

    /**
     * Retrieve a workflow
     * 
     * <p>Fetches details of a specific workflow by its unique identifier **workflowId**
     * 
     * @param workflowId 
     * @param environmentId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerGetWorkflowResponse get(
            @Nonnull String workflowId, @Nullable String environmentId,
            @Nullable String idempotencyKey, @Nullable Options options) {
        WorkflowControllerGetWorkflowRequest request = new WorkflowControllerGetWorkflowRequest(workflowId, environmentId, idempotencyKey);
        RequestOperation<WorkflowControllerGetWorkflowRequest, WorkflowControllerGetWorkflowResponse> operation
              = new WorkflowControllerGetWorkflow.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete a workflow
     * 
     * <p>Removes a specific workflow by its unique identifier **workflowId**
     * 
     * @return The call builder
     */
    public WorkflowControllerRemoveWorkflowRequestBuilder delete() {
        return new WorkflowControllerRemoveWorkflowRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a workflow
     * 
     * <p>Removes a specific workflow by its unique identifier **workflowId**
     * 
     * @param workflowId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerRemoveWorkflowResponse delete(@Nonnull String workflowId) {
        return delete(workflowId, null, null);
    }

    /**
     * Delete a workflow
     * 
     * <p>Removes a specific workflow by its unique identifier **workflowId**
     * 
     * @param workflowId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerRemoveWorkflowResponse delete(
            @Nonnull String workflowId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        WorkflowControllerRemoveWorkflowRequest request = new WorkflowControllerRemoveWorkflowRequest(workflowId, idempotencyKey);
        RequestOperation<WorkflowControllerRemoveWorkflowRequest, WorkflowControllerRemoveWorkflowResponse> operation
              = new WorkflowControllerRemoveWorkflow.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a workflow
     * 
     * <p>Partially updates a workflow by its unique identifier **workflowId**
     * 
     * @return The call builder
     */
    public WorkflowControllerPatchWorkflowRequestBuilder modify() {
        return new WorkflowControllerPatchWorkflowRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a workflow
     * 
     * <p>Partially updates a workflow by its unique identifier **workflowId**
     * 
     * @param workflowId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerPatchWorkflowResponse modify(@Nonnull String workflowId, @Nonnull PatchWorkflowDto body) {
        return modify(workflowId, null, body,
            null);
    }

    /**
     * Update a workflow
     * 
     * <p>Partially updates a workflow by its unique identifier **workflowId**
     * 
     * @param workflowId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerPatchWorkflowResponse modify(
            @Nonnull String workflowId, @Nullable String idempotencyKey,
            @Nonnull PatchWorkflowDto body, @Nullable Options options) {
        WorkflowControllerPatchWorkflowRequest request = new WorkflowControllerPatchWorkflowRequest(workflowId, idempotencyKey, body);
        RequestOperation<WorkflowControllerPatchWorkflowRequest, WorkflowControllerPatchWorkflowResponse> operation
              = new WorkflowControllerPatchWorkflow.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Sync a workflow
     * 
     * <p>Synchronizes a workflow to the target environment
     * 
     * @return The call builder
     */
    public WorkflowControllerSyncRequestBuilder sync() {
        return new WorkflowControllerSyncRequestBuilder(sdkConfiguration);
    }

    /**
     * Sync a workflow
     * 
     * <p>Synchronizes a workflow to the target environment
     * 
     * @param workflowId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerSyncResponse sync(@Nonnull String workflowId, @Nonnull SyncWorkflowDto body) {
        return sync(workflowId, null, body,
            null);
    }

    /**
     * Sync a workflow
     * 
     * <p>Synchronizes a workflow to the target environment
     * 
     * @param workflowId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerSyncResponse sync(
            @Nonnull String workflowId, @Nullable String idempotencyKey,
            @Nonnull SyncWorkflowDto body, @Nullable Options options) {
        WorkflowControllerSyncRequest request = new WorkflowControllerSyncRequest(workflowId, idempotencyKey, body);
        RequestOperation<WorkflowControllerSyncRequest, WorkflowControllerSyncResponse> operation
              = new WorkflowControllerSync.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve workflow step
     * 
     * <p>Retrieves data for a specific step in a workflow
     * 
     * @return The call builder
     */
    public WorkflowControllerGetWorkflowStepDataRequestBuilder getStep() {
        return new WorkflowControllerGetWorkflowStepDataRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve workflow step
     * 
     * <p>Retrieves data for a specific step in a workflow
     * 
     * @param workflowId 
     * @param stepId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerGetWorkflowStepDataResponse getStep(@Nonnull String workflowId, @Nonnull String stepId) {
        return getStep(workflowId, stepId, null,
            null);
    }

    /**
     * Retrieve workflow step
     * 
     * <p>Retrieves data for a specific step in a workflow
     * 
     * @param workflowId 
     * @param stepId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerGetWorkflowStepDataResponse getStep(
            @Nonnull String workflowId, @Nonnull String stepId,
            @Nullable String idempotencyKey, @Nullable Options options) {
        WorkflowControllerGetWorkflowStepDataRequest request = new WorkflowControllerGetWorkflowStepDataRequest(workflowId, stepId, idempotencyKey);
        RequestOperation<WorkflowControllerGetWorkflowStepDataRequest, WorkflowControllerGetWorkflowStepDataResponse> operation
              = new WorkflowControllerGetWorkflowStepData.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
