/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class BulkUpdateSubscriberPreferencesDto {
    /**
     * Array of workflow preferences to update (maximum 100 items)
     */
    @JsonProperty("preferences")
    private List<BulkUpdateSubscriberPreferenceItemDto> preferences;

    @JsonCreator
    public BulkUpdateSubscriberPreferencesDto(
            @JsonProperty("preferences") @Nonnull List<BulkUpdateSubscriberPreferenceItemDto> preferences) {
        this.preferences = Optional.ofNullable(preferences)
            .orElseThrow(() -> new IllegalArgumentException("preferences cannot be null"));
    }

    /**
     * Array of workflow preferences to update (maximum 100 items)
     */
    public List<BulkUpdateSubscriberPreferenceItemDto> preferences() {
        return this.preferences;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Array of workflow preferences to update (maximum 100 items)
     */
    public BulkUpdateSubscriberPreferencesDto withPreferences(@Nonnull List<BulkUpdateSubscriberPreferenceItemDto> preferences) {
        this.preferences = Utils.checkNotNull(preferences, "preferences");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BulkUpdateSubscriberPreferencesDto other = (BulkUpdateSubscriberPreferencesDto) o;
        return 
            Utils.enhancedDeepEquals(this.preferences, other.preferences);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            preferences);
    }
    
    @Override
    public String toString() {
        return Utils.toString(BulkUpdateSubscriberPreferencesDto.class,
                "preferences", preferences);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<BulkUpdateSubscriberPreferenceItemDto> preferences;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Array of workflow preferences to update (maximum 100 items)
         */
        public Builder preferences(@Nonnull List<BulkUpdateSubscriberPreferenceItemDto> preferences) {
            this.preferences = Utils.checkNotNull(preferences, "preferences");
            return this;
        }

        public BulkUpdateSubscriberPreferencesDto build() {
            return new BulkUpdateSubscriberPreferencesDto(
                preferences);
        }

    }
}
